### ISSUE TITLE
RuleProxy invoke with equals get an unexpected result

### ISSUE THREAD

**Issue by wg1j** [j-easy/easy-rules#100]
Hi, 

Here is my code:

```java
@org.jeasy.rules.annotation.Rule
class DummyRule {
    @Condition
    public boolean when() { return true; }

    @Action
    public void then() { }
}

@Test
public void invokEquals() {
    Object rule = new DummyRule();
    Rule proxy1 = RuleProxy.asRule(rule);
    Rule proxy2 = RuleProxy.asRule(proxy1);
  
    assertTrue(proxy1.equals(rule));
    assertTrue(proxy1.equals(proxy1));
    assertTrue(proxy1.equals(proxy2));
}
```

I expected to `false true true`, but the actual is `true false false`. It is totally unexpected that the result of  `proxy1.equals(proxy1)` is **`false`**. 

I check the `equals()` defined in [javadoc](http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html#equals(java.lang.Object)) :

>   **It is *reflexive*: for any non-null reference value `x`, `x.equals(x)` should return `true`.**
>
>   It is *symmetric*: for any non-null reference values `x` and `y`, `x.equals(y)` should return `true` if and only if `y.equals(x)` returns `true`.
>
>   It is *transitive*: for any non-null reference values `x`, `y`, and `z`, if `x.equals(y)` returns `true` and `y.equals(z)` returns `true`, then `x.equals(z)` should return `true`.
>
>   It is *consistent*: for any non-null reference values `x` and `y`, multiple invocations of `x.equals(y)` consistently return `true` or consistently return `false`, provided no information used in `equals` comparisons on the objects is modified.
>
>   For any non-null reference value `x`, `x.equals(null)` should return `false`.

Furthermore, `equals()` always relate to `hashCode()`, and may have influenced to hash-based **`Collection`** or **`Map`**.

Thus,  what do you think about  to override `equals()` and `hashCode()`?, and how to do it?

**Comment by benas** [comment]
The generated proxy does not redefine equals and hashcode methods, it returns the result of those defined in the target object:

https://github.com/j-easy/easy-rules/blob/master/easy-rules-core/src/main/java/org/jeasy/rules/core/RuleProxy.java#L107-L112

You should override equals and hashcode in your rule object.

**Comment by benas** [comment]
Actually we can do the same as `compareTo` method.

[Currently](https://github.com/j-easy/easy-rules/blob/master/easy-rules-core/src/main/java/org/jeasy/rules/core/RuleProxy.java#L116-L124), the proxy looks if the target object overrides `compareTo` and:

* If it is the case, it delegate to the method in the target object
* If not, it uses a [default](https://github.com/j-easy/easy-rules/blob/master/easy-rules-core/src/main/java/org/jeasy/rules/core/RuleProxy.java#L146-L158) comapreTo method based on some criteria

We can do the same for equals and hashcode. We can delegate to the user defined equals/hashcode methods if any, and if no, provide default methods.

This way, the proxy behaviour would be consistent between all methods (equals/hashcode/compareTo) and proxies would equals to themselves (and conform to the contract of equals) even if the user does not override equals/hashcode (like in your example).

What do you think?

**Comment by wg1j** [comment]
It would be just perfect！😃

**Comment by benas** [comment]
Great! I'll plan that for next version.

Thank you for all your valuable feedback!
