### ISSUE TITLE
Easy work flow

### ISSUE THREAD

**Issue by jnsunkersett** [j-easy/easy-rules#101]
Hi,

I went through the documentation and was impressed with your easy, lightweight, pojo based engine.
The annotation and pojo based are the most appealing parts.

But still could the rules be be externalized to an external property file or similar ?

Though I have not used EasyRules practically yet, was contemplating using it more as a WorkFlow engine than a RuleEngine. (cause a workflow is also a series of steps to be taken based on some decision)

So the external file is important, to externalize the flow.

If you are aware of anything similar any redirection will be appreciated.

thanks in advance.
Jeevan

**Comment by benas** [comment]
Hi,

> I went through the documentation and was impressed with your easy, lightweight, pojo based engine.
The annotation and pojo based are the most appealing parts.

Thank you!

> But still could the rules be be externalized to an external property file or similar ?

Yes, this is planned for next release. Please see #36 

> Though I have not used EasyRules practically yet, was contemplating using it more as a WorkFlow engine than a RuleEngine. (cause a workflow is also a series of steps to be taken based on some decision). If you are aware of anything similar any redirection will be appreciated.

There is a project called [easy flows](https://github.com/j-easy/easy-flows) for that. But it is not released yet. It will allow to define workflows as you described. Keep tuned 😉 

Kr
Mahmoud

**Comment by benas** [comment]
Hi @jnsunkersett 

> There is a project called easy flows for that. But it is not released yet.

FYI, Easy Flows project has been released.

Kind regards
Mahmoud

**Comment by benas** [comment]
Hi @jnsunkersett 

Any update on this?

**Comment by jnsunkersett** [comment]
Hi,
I could see / read / checkOut the easy-flows code.However currently busy with some other project (in which I could potentially use easy-flows)
In the meantime, keep up the great work. 
thanksJeevan

On Wednesday, July 5, 2017, 2:16:31 PM GMT+5:30, Mahmoud Ben Hassine <notifications@github.com> wrote:


Hi @jnsunkersett

Any update on this?

**Comment by benas** [comment]
Ok great. Let me know if you need help.

Kr
Mahmoud

**Comment by benas** [comment]
> But still could the rules be be externalized to an external property file or similar ?

@jnsunkersett Now that #36 is implemented, you can store rules in an external resource (file, db) and load them when needed without recompiling the app. You can already give it a try in v3.1 snapshot. Hope this helps!

**Comment by jamie3** [comment]
Looks great

**Comment by eric8words** [comment]
I like the rules engine and the workflow. keep going.

**Comment by benas** [comment]
@eric8words Glad to hear that! Thank you!
