### ISSUE TITLE
RulesEngineBuilder could expose a method to set RulesEngineParameters

### ISSUE THREAD

**Issue by khandelwalankit** [j-easy/easy-rules#102]
I have multiple rules Engine that are running for different services. Each of these rules engine would need different type of parameters (RulesEngineParameters) which i set from property file. Right now i have to invoke setter on each parameter according to builder. But if RulesEngineBuilder can expose a method which can take input as RulesEngineParameter it can set these parameters internally as well.

public RulesEngineBuilder setParameters(RulesEngineParameters rulesEngineParameters){
this.parameters = rulesEngineParameters;
} 

The advantage of this is cleaner client code. Let me know what do you think.

**Comment by benas** [comment]
Have you considered using this constructor:

https://github.com/j-easy/easy-rules/blob/6661401c604eea0e096b749b1f70bc8d747e30fe/easy-rules-core/src/main/java/org/jeasy/rules/core/DefaultRulesEngine.java#L69-L69

?

**Comment by khandelwalankit** [comment]
I don't see DefaultRulesEngine constructor as public in 3.0.0. Have you made it public in newer version?

```
DefaultRulesEngine(final RulesEngineParameters parameters, final List<RuleListener> ruleListeners) {
        this.parameters = parameters;
        this.ruleListeners = ruleListeners;
        this.ruleListeners.add(new DefaultRuleListener());
        if (parameters.isSilentMode()) {
            Utils.muteLoggers();
        }
    }
```

**Comment by benas** [comment]
> Have you made it public in newer version?

Yes, it is public since v3. See "Major Changes" section in release notes: https://github.com/j-easy/easy-rules/releases/tag/easy-rules-3.0.0

I can explain why this is a major change if you want.

**Comment by khandelwalankit** [comment]
Thank you for the info. I see the constructor of DefaultRulesEngine as package-private and not public in v3. Probably that is the reason i was not able to access it.

**Comment by benas** [comment]
Yes sorry, my mistake. In v3, the class has been made public with only a default constructor. The constructor your are looking for was added in bb924488735533f8a5992c4551143fb8bde66ea3

It is coming in v3.1, you can see it in the snapshot version already.

**Comment by khandelwalankit** [comment]
Thanks for clarification. Excited for upcoming v3.1
