### ISSUE TITLE
recommend one better rule engine

### ISSUE THREAD

**Issue by wangwei86609** [j-easy/easy-rules#103]
https://github.com/wangwei86609/osmanthus

**Comment by wangwei86609** [comment]
come to see the better rule engine

**Comment by benas** [comment]
Hi @wangwei86609 

Great to see you providing an alternative to Easy Rules! This is what makes OSS beautiful.

Can you elaborate how it is better? What are the pros/cons of each solution and how do they compare?

We didn't want to mix rules and flows in the same engine in [jeasy](jeasy.org). Our goal is to design small tools that do one thing and that are composable. For example:

* You can compose a flow of rules using easy rules and easy flows
* You can run easy batch jobs in easy jobs server
* etc

This is better for reusability, testability and maintainability.

Is there a good reason you decided to mix rules and flows in osmanthus?

Kind regards
Mahmoud

**Comment by wangwei86609** [comment]
Hi @benas 
Thanks for your advice, I don't mix rules & flows, this is the problem from my description.
I will answer your question in document, but you have to wait some days

Kind regards 
Wei
