### ISSUE TITLE
Why you sometimes extend BasicRule and sometimes use annotation?

### ISSUE THREAD

**Issue by 3amprogrammer** [j-easy/easy-rules#105]
This question might be silly, but I barely know Java and I want to port this awesome package to my primary language. The only reason I've come up with is you can give your rules' methods some meaningful names.

Thanks in advance for any clarification.

**Comment by benas** [comment]
Hello,

There is no particular reason. When I started easy rules, there was only the programmatic way (extending `BasicRule` class or implementing `Rule` interface) of defining rules. Then I introduced the annotation programming model which is more declarative.

I kept both approches for felxibility. The user has two options and he can choose what is better for him.

Just curious, which language do you want to port easy rules to? May I help?

Kr
Mahmoud

**Comment by 3amprogrammer** [comment]
Hello,

thanks for the reply. I will do my best to port this to PHP. I was looking for a solution to my business problem and I have found the term Rules Engine. There are a few engines for PHP, but I don't like they way you declare rules using them.

We also have annotations, but I don't think they are supported natively as good as in Java, thus I wanted to understand why you used them and whether or not I should reflect this behavior.

It is possible I will have some questions in the process, so you can contribute clearing my doubts.

**Comment by benas** [comment]
Sure, I would love to help.
