### ISSUE TITLE
Use SLF4J instead of java.util.logging

### ISSUE THREAD

**Issue by sanmibuh** [j-easy/easy-rules#113]
Using java.util.logging for logging has a lot of side effect. See this
http://glauche.de/2009/09/09/java-util-logging-vs-slf4j/

For example, we are using this lib into a Grails 2 application. But it doesn't use our logging config. We need to replicate logs formats, because we are using Kibana and we need a predefined format.

I think it could be great using slf4j instead of  java.util.logging. This resolves our problem and the performance should be better.

**Comment by benas** [comment]
Hi,

As I said [here](https://github.com/j-easy/easy-rules/issues/91#issuecomment-307887364), I don't exclude replacing JUL with SL4J.

Thank you for the PR! I added a couple of notes there.
Please take a look to update the PR and it will be ready to merge.

Kr
Mahmoud

**Comment by benas** [comment]
Hi,

I've merged your PR, thank you!

Hence, I'm closing this issue.

Kr
Mahmoud

**Comment by sanmibuh** [comment]
Thank you :)

**Comment by wg1j** [comment]
Hi, 

https://github.com/j-easy/easy-rules/blob/master/easy-rules-core/src/main/java/org/jeasy/rules/core/DefaultRulesEngine.java#L244
```java                    
fact.getValue() == null ? "null" : fact.getValue().toString()
```
I think `String.valueOf(fact.getValue())` is easier here 😀

**Comment by benas** [comment]
@wg1j good point!

**Comment by benas** [comment]
@wg1j done here: 4b7ed47da32e2034c56ca2904af16b79d5da75ce
