### ISSUE TITLE
i want to ask a stupid question on class "BasicRule"

### ISSUE THREAD

**Issue by zhhaojie** [j-easy/easy-rules#117]
now : 
`public class BasicRule implements Rule, Comparable<Rule>`
 why not : 
`public class BasicRule implements Rule`

did have  some another reasons to implements Comparable<Rule> again ?

thanks

**Comment by benas** [comment]
Hi,

There are no stupid questions, only stupid answers 😄 
You are right, no need for implementing Comparable.

This has been fixed here (https://github.com/j-easy/easy-rules/pull/111) and will be included in the next version 3.1

Does this answers your question?

Kr
Mahmoud

**Comment by zhhaojie** [comment]
you are so kind . that's what i want .
