### ISSUE TITLE
Pluggable Actions

### ISSUE THREAD

**Issue by khandelwalankit** [j-easy/easy-rules#119]
I had asked this question on gitter briefly but wanted to elaborate on proposition of actions. 
As per my understanding Rule is composition of one condition and multiple actions. One way to look at rules engine is : 

Rule : DrivingRights
condition : age > 18 && country = USA || UAE
action : isActive = true

Rule : VotingRights
condition : age > 18 && country = USA || UAE
action : isActive = true 

Rule : DrinkingRights
condition : age > 18 && country = USA
action : isActive = true 

This looks possible with current design. But the other way to address this is

Rule : AgeGreaterThan18_1 
condition : age > 18 & country = USA
action1 : activateDrivingRights
action2 : activateVotingRights
action3 : activateDrinkingRights

Rule : AgeGreaterThan18_2
condition : age > 18 & country = UAE
action1 : activateDrivingRights
action2 : activateVotingRights

which requires actions to be separate components like rules and can be plugged and removed from any rule. This in current design would lead to a lot of boiler plate code. My proposition is just like Engine require a set of rules to run. A rule should have a set of actions which could be available at runtime. Let me know what you think of it.

**Comment by benas** [comment]
Hi @khandelwalankit 

This is a good idea. In the very first stage of the project, we had separate concepts for conditions and actions. But then we decided to make a rule encapsulate those as a unit. You can find some other details in #40 .

But as you said, what you are looking for is possible with the current design, and you can always extract duplicate logic in separate action class and reuse it. Does this make sense?

Kr
Mahmoud

**Comment by cemo** [comment]
We had a similar problem and I resolved this by introducing a new 2 interface. 

```
public interface Condition {
  Boolean evaluate(Facts facts);
}

public interface Action {
  void execute(Facts facts) throws Exception;
}

And 

public class ActionConditionRule implements Rule {

  private final String ruleContext;

  private final Condition condition;

  private final Action action;

  private final Integer priority;

  public ActionConditionRule(String ruleContext, Condition condition, Action action, Integer priority) {
    this.ruleContext = ruleContext;
    this.condition = condition;
    this.action = action;
    this.priority = priority;
  }

  @Override
  public String getName() {
    return ruleContext;
  }

  @Override
  public String getDescription() {
    return "";
  }

  @Override
  public int getPriority() {
    return priority;
  }

  @Override
  public boolean evaluate(Facts facts) {
    return condition.evaluate(facts);
  }

  @Override
  public void execute(Facts facts) throws Exception {
    action.execute(facts);
  }

  @Override
  public int compareTo(Rule rule) {
    return Integer.compare(priority, rule.getPriority());
  }
}

```

In this situation you just need create a new CompositeAction class which is executing all actions it contains.

**Comment by benas** [comment]
@cemo These interfaces are exactly the same I used in the early stage of the project.

> In the very first stage of the project, we had separate concepts for conditions and actions. But then we decided to make a rule encapsulate those as a unit.

Probably my decision is no that good! Even though I said [here](https://github.com/j-easy/easy-rules/issues/40#issuecomment-221198737) that it is easier to encapsulate conditions and actions in a rules, this does not mean they cannot be in a separate concepts. So I might be wrong!

In hindsight, I think if we decouple conditions and actions from rules, we can have several advantages:

* reusability as shown by @khandelwalankit 
* flexibility as suggested by @cemo (we can design a 'all or nothing' composite rule (like the current `CompositeRule`), or 'at least one' composite rule (like suggested in #122 ), etc)
* possibility to introduce Rule EL ( as in #44 )

In regards to EL, I was thinking of something like:

```java
class ELCondition implements Condition {
   private String elExpression;
   public ELCondition(String elExpression) {
      this.elExpression = elExpression;
   }

   public Boolean evaluate(Facts facts) {
      // use MVEL, SpringEL, JEXL, etc to evaluate elExpression on the given facts
   }
}
```

Same for actions. Also, by having conditions and actions decoupled, a rule may use EL for the condition but regular java code for actions.

@khandelwalankit @cemo What do you think?

**Comment by benas** [comment]
I'm definitely convinced with (re)introducing separate `Condition/Action` concepts. In addition to the benefits I mentioned in my previous comment, I can add unit testing! Meaning one can unit test conditions and actions in isolation based on the given facts.

Anyway, here we go. I've just deployed a new snapshot version with these additions. You can see it in action [here](https://github.com/j-easy/easy-rules/tree/master/easy-rules-tutorials/src/main/java/org/jeasy/rules/tutorials/airco).

@khandelwalankit @cemo It would be great if you can give it a try tell me what do you think. Many thanks upfront!

**Comment by cemo** [comment]
We have migrated our code base into current snapshot. It is working properly. We have cleaned a great amount of codes from our codebase. A milestone release would be cool :)

**Comment by benas** [comment]
> We have migrated our code base into current snapshot. It is working properly. We have cleaned a great amount of codes from our codebase

Oh great! Glad to hear that.

> A milestone release would be cool :)

Sure! I will try to publish a first RC this weekend. I'll keep you posted.

**Comment by benas** [comment]
@khandelwalankit 

> My proposition is just like Engine require a set of rules to run. A rule should have a set of actions which could be available at runtime. Let me know what you think of it.

I guess the `Condition` / `Action` APIs that were introduced are what you are looking for.

I'm preparing a release of v3.1 in the next few days. It would be great if you can give a try to the feature you requested and submit your feedback.

**Comment by khandelwalankit** [comment]
@benas : My apologies, i am out of town for vacation and could not respond earlier to this. I will try to test it and send in my feedback soon. On a side note, can we have annotation processing for Condition and Action as well and use it with @Rule annotation?

**Comment by benas** [comment]
@khandelwalankit No worries, enjoy your vacation!

This will go into v3.1. In case of any issue, it will be for v3.2.

> On a side note, can we have annotation processing for Condition and Action as well and use it with @rule annotation?

Not sure I fully understand this. Do you mean if we can mix and match the usage of annotations and APIs in the same rule? Please open separate issue for that.
