### ISSUE TITLE
RulesEngine  can run rules in parallel

### ISSUE THREAD

**Issue by xiaobaitany** [j-easy/easy-rules#120]
Now, RulesEngine  runs rules one by one.  I hope the RulesEngine supports running the rules in parallel.

**Comment by benas** [comment]
Hi,

Yes, this is by design. Production systems are intended to work this way in order to a rule to add/modify/remove facts so next rules can be triggered or not. If we run rules in parallel, this cannot be achieved anymore.

Does this make sense?

Kr
Mahmoud

**Comment by benas** [comment]
I am closing this issue for now.

If you have any question, you can reopen it.
