### ISSUE TITLE
cast friendly Facts

### ISSUE THREAD

**Issue by cemo** [j-easy/easy-rules#123]
Our codes are requires getting objects from facts but each time we need to cast to use it like this.

```
Coupon coupon = (Coupon)facts.get("coupon");
```

This is unfortunately causing ugly codes and suppress warnings in editor. A change in the implementation would be very beneficial

```

    public Object get(String name) {
        Objects.requireNonNull(name);
        return facts.get(name);
    }

to 

    public <T> T  get(String name) {
        Objects.requireNonNull(name);
        return (T) facts.get(name);
    }

```

What do you think?

**Comment by benas** [comment]
Sure! Good idea.

I will include this in next release. I was planning to work on easy rules this week.

If you want to contribute, you are welcome!

Kr
Mahmoud

**Comment by benas** [comment]
This issue has been implemented in version 3.1.0-SNAPSHOT.

@cemo It would be great if you can give it a try and tell me if this is ok for you. Thanks in advance!

**Comment by cemo** [comment]
tested. :shipit:

**Comment by benas** [comment]
Great! thank you for taking time to test 👍 

Keep tuned for next release.
