### ISSUE TITLE
Make DefaultRulesEngine not final

### ISSUE THREAD

**Issue by cemo** [j-easy/easy-rules#124]
Please make `DefaultRulesEngine` class not final and `apply` method protected. We had to duplicated a great amount code in order to add some extra behaviours. 
Delegating is not possible since apply method is private.

**Comment by cemo** [comment]
By the way, If you are OK with this issue, we can submit PR's to fix this issue and other issues we had we submitted.

**Comment by benas** [comment]
> Please make DefaultRulesEngine class not final and apply method protected.

This is by design ([same](https://github.com/j-easy/easy-rules/commit/40e46172ebb8ed18c704746985bf6ba659004d9f) for the upcoming inference engine), we don't want to make it possible to subclass the engine and modify its behaviour after we tested it. But we have to make sure you can extend it through some extension points (params + listeners). This is somehow the open closed pricinple. Does this make sense?

> We had to duplicated a great amount code in order to add some extra behaviours.

If this is the case, then the current design of easy rules is **not** good! Which code have you had to duplicate?

**Comment by cemo** [comment]
Ok, would you make it protected apply method?

**Comment by benas** [comment]
> Ok, would you make it protected apply method?

I am not sure I understand, even if we make the method protected, you would not be able to subclass the engine since the class is final.

> for adding new behaviour

What is this new behaviour? Is it possible to add it using one of the listeners?
If not, may be we need more finer grained listeners?

**Comment by cemo** [comment]
Sorry I was not clear. We would like to fetch some entities such as user coupons from database and iterate with default engine. However rules are usually tend to work for a single input instead of list of it. We had to implement a new engine `IteratingEngine`. This is delegating evaluation per entity to `DefaultEngine`. Previous work was not delegating friendly since we had to change apply method. Current implementation seems better and I will let you know about details. Let's close for now and in case a need I will let you know.

**Comment by benas** [comment]
> Sorry I was not clear. We would like to fetch some entities such as user coupons from database and iterate with default engine. However rules are usually tend to work for a single input instead of list of it. We had to implement a new engine IteratingEngine. This is delegating evaluation per entity to DefaultEngine. 

Ok I see, interesting use case! I had a similar requirement when I tried to implement the [fizzbuzz](https://github.com/j-easy/easy-rules/wiki/fizz-buzz) tutorial. Probably it can help? I did the iteration myself, I would change numbers with coupons [here](https://github.com/j-easy/easy-rules/blob/master/easy-rules-tutorials/src/main/java/org/jeasy/rules/tutorials/fizzbuzz/FizzBuzzWithEasyRules.java#L46-L52).

> Previous work was not delegating friendly since we had to change apply method. Current implementation seems better and I will let you know about details. Let's close for now and in case a need I will let you know.

Sure, please don't hesitate. And thank you for your time and all your suggestions!

**Comment by cemo** [comment]
>  Probably it can help? I did the iteration myself, I would change numbers with coupons here.

Same requirement :) We want to ship our engine as part of infrastructure. We are considering implementing generic campaigns/rule sets in future :) If you interested with IteratingEngine we can submit a PR as well.
