### ISSUE TITLE
How to get rules that were applied (evaluated to true)?

### ISSUE THREAD

**Issue by 3amprogrammer** [j-easy/easy-rules#125]
I should rather ask: how would you implement such a feature, following good OO design?

**Comment by cemo** [comment]
https://github.com/j-easy/easy-rules/blob/master/easy-rules-core/src/main/java/org/jeasy/rules/api/RulesEngine.java#L64-L68

**Comment by 3amprogrammer** [comment]
Thanks, I dont know how I’ve missed that.

**Comment by 3amprogrammer** [comment]
Thanks, I dont know how I’ve missed that.

**Comment by benas** [comment]
@cemo thank you for your quick reply!

@3amprogrammer You've got the right answer, `check` method is the way to go.

**Comment by benas** [comment]
@3amprogrammer You might also use a rule listener for that. Something like:

```java
public class AppliedRuleListener implements RuleListener {
    
    private Rule appliedRule;

    @Override
    public void afterEvaluate(Rule rule, Facts facts, boolean evaluationResult) {
        if(evaluationResult) {
            appliedRule = rule;
        }
    }

    public Rule getAppliedRule() {
        return appliedRule;
    }

   // other methods in RuleListener interface 
}
```

After firing the rules engine, you can ask this listener to get which rule has been applied.

Hope this helps!
