### ISSUE TITLE
Use case for Action annotation order property

### ISSUE THREAD

**Issue by 3amprogrammer** [j-easy/easy-rules#128]
Could you give me some example when defining an order might be useful? 

For now it seems to me like a fancy way of doing this:
```java
@Action
public void then() throws Exception {
    then0();
    then2();
    then3();
}

protected void then0() throws Exception {
    actionSequence += "0";
}

protected void then1() throws Exception {
    actionSequence += "1";
}

protected void then2() throws Exception {
    actionSequence += "2";
    executed = true;
}
````
Again, I'm porting this to PHP, so I would like to have full understanding of the design choices. Thanks!

**Comment by benas** [comment]
This example is from tests, it is a way to assert that actions are executed in order (not the best way, I should use mockito `InOrder` class).

The design choice is the following: IMO, it is better to allow a rule to define multiple actions (and their execution order) than one single action that does everything.

> Could you give me some example when defining an order might be useful?

For example, consider this rule:

```java
class OrderPlacedRule {
   
   @Condition
   public isOrderPlaced() { ... }

   @Action(order = 1)
   public updateStock() { ... }

   @Action(order = 2)
   public sendConfirmationEmail { ... }
}
```

In this fictitious example, you might want to reorder actions according to business rule change. Having small actions is better to reuse, compose and unit test.

Does this helps?

**Comment by 3amprogrammer** [comment]
Sure, this:
> it is better to allow a rule to define multiple actions (and their execution order) than one single action that does everything.

has convinced me, thanks!
