### ISSUE TITLE
MVEL related class files are missing

### ISSUE THREAD

**Issue by jinjingfarm** [j-easy/easy-rules#129]
It seems to me that MVEL related class files are missing in the easy-rules-core-3.1.0.jar file.

**Comment by alwajdi** [comment]
I believe you need to include easy-rules-mvel as your dependency. I am testing the MVEL rule feature and so far no problems with it.

**Comment by jinjingfarm** [comment]
alwajdi: thanks for the help. However, I cannot locate the easy-rules-mvel-x.x.x.jar.

**Comment by jinjingfarm** [comment]
found the jar file.

**Comment by alwajdi** [comment]
you're not using maven?

**Comment by jinjingfarm** [comment]
No, not yet. I am planning to use it in the near future. Thanks again.
