### ISSUE TITLE
Proposal: Read YAML rule descriptor from String

### ISSUE THREAD

**Issue by paulbrejla** [j-easy/easy-rules#133]
Hi,

first of all thanks for this project, I've found it incredibly helpful. 

My current project has the requirement to store rule descriptors in YAML alongside entities in the database. The current implementation of the _MVELRuleFactory_ only supports loading rule descriptors from the file system. I think it would be useful if _MVELRuleFactory.createRuleFrom_ would also accept rule descriptors as String.

What do you think? I'd be happy to submit a PR for this.

**Comment by benas** [comment]
Hi @paulbrejla 

Yes! the factory should be able to create rules from a `java.io.Reader`, then the user can choose a StringReader or FileReader or any reader implementation.

Good suggestion, thank you!

> I'd be happy to submit a PR for this.

You are welcome! I'll plan it for v3.2

Best regards,
Mahmoud
