### ISSUE TITLE
Load multiple rules from a single yaml file

### ISSUE THREAD

**Issue by jreyes256** [j-easy/easy-rules#138]
How can I create a list of rules from a rules.yml file?

**Comment by benas** [comment]
That was planned. Let me add it to the upcoming v3.2.

Thank you for your suggestion!

**Comment by benas** [comment]
If you want to contribute, you are welcome!

**Comment by benas** [comment]
Hi @jreyes256 

I added the ability to load multiple rules at once from a rules descriptor (see `MVELRuleFactory#createRulesFrom`). I'm releasing v3.2 soon but you can already test this feature in the latest snapshot if you want.

Kr
Mahmoud

**Comment by Na3blis** [comment]
I tried to to put multiple rules into a single file. However, it only loads the last file. If I have two rules then It loads the second. If I then put a third rule in, the second no longer loads, only the third. Is there a different format for getting multiple rules to load from a file? All I did was combine two different files into a single file and tried using `MVELRuleFactory.createRulesFrom(reader)`

**Comment by benas** [comment]
Is your rules file correctly formatted? Yaml documents should be separated by "---" when combined in the same file. I have a passing test here:

* The input rules file: https://github.com/j-easy/easy-rules/blob/master/easy-rules-mvel/src/test/resources/rules.yml
* The test that loads both rules successfully: https://github.com/j-easy/easy-rules/blob/master/easy-rules-mvel/src/test/java/org/jeasy/rules/mvel/MVELRuleFactoryTest.java#L43

**Comment by Na3blis** [comment]
Ah, I did not realize the `---` requirement. Thanks, I added that to my yaml file and it worked immediately! Thanks for adding this ability!

**Comment by ruchichhabra009** [comment]
@benas 
I am trying to use this feature, using snapshot version- but I am getting this error.

**Comment by ruchichhabra009** [comment]
testCreateFact(com.vmn.capi.validation.service.FactWrapperTest)  Time elapsed: 0.168 s  <<< ERROR!
org.yaml.snakeyaml.composer.ComposerException: 
expected a single document in the stream
 in 'reader', line 2, column 1:
    name: "title available rule"
    ^
but found another document
 in 'reader', line 8, column 1:
    ---
  
        at com.vmn.capi.validation.service.FactWrapperTest.testCreateFact(FactWrapperTest.java:20)

**Comment by benas** [comment]
please provide the complete file you are trying to load.

**Comment by ruchichhabra009** [comment]
Hi Mahmoud,

Thank you so much for responding so quickly. Please see below attached file
which I am trying to use to validate the content.

Thanks
Ruchi

**Comment by benas** [comment]
I can't see any attached file. Can you share it as a comment?

**Comment by ruchichhabra009** [comment]
---
name: "title available rule"
description: "title sould not be empty"
priority: 1
condition: "title != null"
actions:
  - "System.out.println(\"Title value is available\")"
---
name: "title length check"
description: "title length should be less than 255 characters"
priority: 2
condition: "title.toString().length() < 255 && title.toString().length() > 0"
actions:
  - "System.out.println(\"title value is within range\")"

**Comment by ruchichhabra009** [comment]
[title-rule.yml.zip](https://github.com/j-easy/easy-rules/files/1929605/title-rule.yml.zip)

**Comment by benas** [comment]
thanks. I see nothing wrong with the file. But I see from the error:

```
expected a single document in the stream
```

Looks like the yaml parser is expecting a single document. Are you sure you are using `MVELRuleFactory.createRulesFrom` (in plural) and not `MVELRuleFactory.createRuleFrom` ?

**Comment by ruchichhabra009** [comment]
Thank you Mahmoud, 
Yes you are right, I missed this information. Do you have link for the documentation of new features added. I think, I am missing those. I am reading through the issues and enhancement page.

**Comment by benas** [comment]
Hi,

Glad to be of help. I updated the wiki with an example of how to load multiple rules from a file: https://github.com/j-easy/easy-rules/wiki/expression-language-support#create-rules-from-a-rule-descriptor.

> Do you have link for the documentation of new features added

Yes, the release notes here: https://github.com/j-easy/easy-rules/releases/tag/easy-rules-3.2.0

Kr,
Mahmoud

**Comment by jreyes256** [comment]
I want to contribute to this library, I did my thesis applying systems of rules

**Comment by benas** [comment]
Oh great thanks your are welcome! Take a look at open issues and choose what ever you think is good for you to work on.

**Comment by afshansuheel** [comment]
Hi ,

i getting below error

> [CompletionException: java.lang.IllegalArgumentException: Rule 'org.jeasy.rules.api.Rules' is not annotated with 'org.jeasy.rules.annotation.Rule']

//Java code
` Rules testRule = MVELRuleFactory.createRulesFrom(new FileReader(file));
 Rules rules = new Rules();
 rules.register(testRule);
//create a default rules engine and fire rules on known facts
RulesEngine rulesEngine = new DefaultRulesEngine();
rulesEngine.check(rules, facts);`

//yaml file
`name: "test rule1"
description: "Always"
priority: 1
condition: "true"
actions:
  - "System.out.println(\"Good!\");"
---
name: "test rule2"
description: "Always"
priority: 2
condition: "true"
actions:
  - "System.out.println(\"Great!\");"`

**Comment by afshansuheel** [comment]
Hi,
I am getting below error

> [CompletionException: java.lang.IllegalArgumentException: Rule 'org.jeasy.rules.api.Rules' is not annotated with 'org.jeasy.rules.annotation.Rule']

//java code

>  Rules testRule = MVELRuleFactory.createRulesFrom(new FileReader(file));
    Rules rules = new Rules();
    rules.register(testRule);
    //create a default rules engine and fire rules on known facts
    RulesEngine rulesEngine = new DefaultRulesEngine();
    rulesEngine.check(rules, facts);

**Comment by docXU** [comment]
@alfiyafreen you cant register Rules into Rules!

**Comment by pallavialuri** [comment]
hi i am trying to interate through the multiple rules in the .yml file ...i am stuck at how to fire a particular rule from .yml file depending on the condition...can you please help me out on how to fire a particular rule from the .yml file..i am unable to figure out the method to fire a particular rule...

**Comment by pallavialuri** [comment]
i am getting the following error while running the class...

Exception in thread "main" while parsing a block mapping
 in 'reader', line 2, column 1:
    name: "order TCU rule"
    ^
expected <block end>, but found '<scalar>'
 in 'reader', line 5, column 27:
    condition: "device == TCU";
                              ^

	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:572)
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148)
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:214)
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:144)
	at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:85)
	at org.yaml.snakeyaml.constructor.BaseConstructor.getData(BaseConstructor.java:123)
	at org.yaml.snakeyaml.Yaml$1.next(Yaml.java:547)
	at org.jeasy.rules.support.YamlRuleDefinitionReader.loadRules(YamlRuleDefinitionReader.java:71)
	at org.jeasy.rules.support.AbstractRuleDefinitionReader.read(AbstractRuleDefinitionReader.java:42)
	at org.jeasy.rules.mvel.MVELRuleFactory.createRules(MVELRuleFactory.java:144)
	at org.jeasy.rules.mvel.MVELRuleFactory.createRules(MVELRuleFactory.java:133)
	at org.jeasy.rules.tutorials.device.Launcher.main(Launcher.java:44)

i am also including the .yml file and the main executable class


[files.zip](https://github.com/j-easy/easy-rules/files/3351633/files.zip)

**Comment by pallavialuri** [comment]
i also want to call methods of diff classes as part of action that needs to be implemented in .yml file..could someone please help me with that as well..thank you in advance..

**Comment by pallavialuri** [comment]
can i also know how to fire a particular rule depending on a condition when there are 2 or more rule defined in .yml file..thank you in advance...
