### ISSUE TITLE
NPE If i add Fact with null value and use annotation

### ISSUE THREAD

**Issue by bpoussin** [j-easy/easy-rules#139]
When we use annotation in pojo for argument and in facts i push null for one or more fact, there is NPE when easy-rules try to call method. 

This issue is corrected in PR  #137

**Comment by benas** [comment]
Hi @bpoussin 

Thank you for reporting and fixing this issue 👍 Congrats on your First PR!
I added you to the contributors list: cf66bd6eb169f11d43551fb7abe2f9097da2bca9

I'm releasing v3.2 soon. Your fix will be included. Stay tuned 😉 

Kind regards,
Mahmoud
