### ISSUE TITLE
Regarding Rule Execution

### ISSUE THREAD

**Issue by aroraShru** [j-easy/easy-rules#140]
Hi,

Currently i have scenario in which i have some calculation Rules and some matching rules
Point 1. Calculation rules will do some calculation based on some attributes present in the fact. 
Point 2. All the calculation Rules must be evaluated for given fact and set some other attributes in fact.
Point 3. Matching rules will match the fact with existing data using calculated attributes from calculation rules. 
Point 4. If one of the rule is matched, the other matching rules should not be evaluated.
Point 5 if no matching rule meets the condition, the fact should be inserted in database.
Point 5. Matching rule can change the attributes used in point 1 (Meaning all the calculations should be done again for that fact, starting from Point 1)

To achieve this, i am using InferenceEngine and skipOnFirstAppliedRule.
initially the skipOnFirstAppliedRule is set to false, when all the calculation rules have completed evaluation, i am setting skipOnFirstAppliedRule to true ( before matching rules start)
in every matching rule, i am setting skipOnFirstAppliedRule as false again if any attribute which is used in point 1 is updated.

Can you suggest any better way to do this?
As of now skipOnFirstAppliedRule is tied to engine. My requirement is to have it with a specific group of rules. 

Thanks,
Arora

**Comment by benas** [comment]
Hi,

It's the first time I see a scenario where the `skipOnFirstAppliedRule` is set and reset dynamically. Clever idea!



> Can you suggest any better way to do this?
> As of now skipOnFirstAppliedRule is tied to engine. My requirement is to have it with a specific group of rules.

What you are looking for is probably the `ActivationRuleGroup` coming in v3.2 (see details [here](https://github.com/j-easy/easy-rules/issues/122#issuecomment-352177775)). This concept and other `CompositeRule` implementation may help you in your use case.

Does this help?

**Comment by aroraShru** [comment]
Hi, Thanks a lot for the information! Yes, ActivationRuleGroup can help in this case.
For now i will keep on setting skipOnFirstAppliedRule dynamically. 

Thanks
