### ISSUE TITLE
multiple rules of same name are ignored

### ISSUE THREAD

**Issue by yossioz** [j-easy/easy-rules#149]
Hi...

I saw that Rules class use a Set<Rule> hence multiple rules with the same name are ignored and only the first one is executed.

is there a workaround for this issue ? is there a chance to change Rules class to be an interface and anyone could implements its own Rules container(one can use rules as Set the other can use it as List)

BR,

**Comment by jimchou800** [comment]
```java
        // create rules
        MVELRule ageRule = new MVELRule()
                .name("age rule")
                .description("Check if person's age is > 18 and marks the person as adult")
                .priority(1)
                .when("person.age > 18")
                .then("person.setAdult(true);fuck");    // ------ look here ----/
        MVELRule alcoholRule = MVELRuleFactory.createRuleFrom(new FileReader("src/main/java/org/jeasy/rules/tutorials/shop/alcohol-rule.yml"));

        // create a rule set
        Rules rules = new Rules();
        rules.register(ageRule);
        rules.register(alcoholRule);

```

and the console print :
```
[main] INFO org.jeasy.rules.core.DefaultRulesEngineListener - Fact { person : Person{name='Tom', age=14, adult=false} }
[main] INFO org.jeasy.rules.core.DefaultRulesEngineListener - Rules evaluation started
[main] INFO org.jeasy.rules.core.DefaultRuleListener - Rule 'age rule' triggered
[main] INFO org.jeasy.rules.core.DefaultRuleListener - Rule 'age rule' performed successfully
```

performed  successfully ?? Why did not throw an exception？

**Comment by yossioz** [comment]
@jimchou800  how is that related to my question ?
I created a rule (using annotation). 
"Rules" class is used as a container for a set of rules. 
Since the implementation uses a **Set** to store the rules, a rule of the same type/name is ignored.
my question: can Rules class could be changed to interface, so everyone could create its own implementation for Rules class(one could use Set, while other could use List)

I will try to explain my problem with the current implementation: 
I created an _EqaulRule_ which get as parameter a value to test if it _equals_ to another parameter.
Now i have a use-case when i need to test "equals" on more than one value, 
e.g: **RuleEquals**(Object.getPrice(), 200) and another rule, **RuleEquals**(Obect.getName(), "MyName")
 Now since Rules class uses a Set to store the rules(Set make sure ONLY single rule of the same name will be store), only one rule is executed, while i need both rules to be executed.

**Comment by benas** [comment]
A `Rules` encapsulates a set of rules and represents a rules **namespace**. Rules must have a unique name within this namespace. That's why we use a `Set` as a container for rules.

> my question: can Rules class could be changed to interface, so everyone could create its own implementation for Rules class(one could use Set, while other could use List)

Yes, Rules can be an interface but in that case, it would be clearly documented that implementations must ensure rule uniqueness within the namespace.

> Now i have a use-case when i need to test "equals" on more than one value,

I see your rules acts on facts of different types (numbers and strings), so for me those are different rules unless you want to make your rule generic.
