### ISSUE TITLE
Can i compare Set<Byte> with String in java and rules?

### ISSUE THREAD

**Issue by syaimaamri** [j-easy/easy-rules#152]
**I have a Java class as below**

      public class Mart implements MartInterface {

         private Set<Byte> visit;
         private Set<Byte> type;
         //
      }
**and to create Drools rule to compare the byte with**

     String REF_VISIT_RESULT = "1"
     String REF_TYPE_RESULT = "2"
**and the set of array for example [1, 2, 3]

the rules will be something like**

    rule "rule 1"
       dialect "java"
       when
       mart : Mart (visit == REF_VISIT_RESULT, type == REF_TYPE_RESULT)

    then
        System.out.println("//error");
    end

**Can i compare Set Byte with Lookup String in drools? Please help to create the .drl file**

**Comment by benas** [comment]
This is better asked on drools issue tracker.
