### ISSUE TITLE
Need contains method with Facts

### ISSUE THREAD

**Issue by ruchichhabra009** [j-easy/easy-rules#153]
Hi @benas 
Please add hashmap's "contains" method in Facts class. I need to make lot of changes for creating customized Facts class.

Thank you so much in advance
Ruchi

**Comment by benas** [comment]
Hi, 

I'm not sure we need this method since we have `org.jeasy.rules.api.Facts#asMap` right?

Have you tried:

```
Facts facts = // some facts
facts.asMap().containsKey("myKey");
```

?

**Comment by benas** [comment]
There is no need for a `contains` method since facts can be accessed using `asMap` as shown in the previous comment. I'm closing this issue for now.
