### ISSUE TITLE
getListeners/getRulesEngineListeners should return a unmodifiable list of listeners

### ISSUE THREAD

**Issue by benas** [j-easy/easy-rules#157]
As of v3.1, it is possible to get listeners from the rules engine and modify the list. This may have an undesirable (nasty!) side effect. 

`org.jeasy.rules.api.RulesEngine#getRuleListeners` and `org.jeasy.rules.api.RulesEngine#getRulesEngineListeners` should return a unmodifiable list or a copy of the listeners.

Same for `org.jeasy.rules.api.RulesEngine#getParameters`.

**Comment by khandelwalankit04** [comment]
@benas : What kind of side effects are being discussed here? Also, do you think as a framework we can restrict easy rules to only use immutable data structures?

**Comment by WayneCui** [comment]
Right now, I used `org.jeasy.rules.api.RulesEngine#getRulesEngineListeners#clear` to remove `DefaultRulesEngineListener`.  It's wired, but it's the fact, as I don't want to output some of the logs. If  `org.jeasy.rules.api.RulesEngine#getRuleListeners` and `org.jeasy.rules.api.RulesEngine#getRulesEngineListeners` return a unmodifiable list or a copy of the listeners, would you please add a new methods to override or remove the `DefaultRulesEngineListener` ? ;-)

**Comment by benas** [comment]
@khandelwalankit04 Let's say you register a listener that does some validation or security checks on  rules before applying them. Then, by mistake, you (or someone else) get the listeners list from the engine and clear it. Your validation logic is gone.

By returning an unmodifiable list, this side effect is eliminated (See tests in 
https://github.com/j-easy/easy-rules/commit/00f52b388c69f46815046d3a981fcf5cba1e5f3e).
