### ISSUE TITLE
get rule configuration and results from rule execution/validation as a json object

### ISSUE THREAD

**Issue by dagframstad** [j-easy/easy-rules#163]
It would be a nice addtion if the RuleEngine could return a json-object describing how the rules are configured. This json could then be used to make a graph in a frontend using d3js (or other suitable tools).

Likewise it would be cool if a similar json could be returned from a rule execution, making it possible to vizualize the indiviual executions.

Just an idea. I don't have the time to work on it now, but if anyone else has...

**Comment by ruchichhabra009** [comment]
@dagframstad 

I have created something sort of that, using listener's afterEvaluate method. For each rule, I am creating an object and adding it to the list. Then returning it as JSON response. I can provide more detail if you need but the response should be specific to the consumer and should not be added here in this.

**Comment by dagframstad** [comment]
@ruchichhabra009 Great. Why not post an example here so we all can see how you have done it. Maybe it can go into the documentation as an example on how to use easy-rules.

**Comment by dcmr** [comment]
I want to return json result  after fire rules .Could you paste a example? thanks a lot

**Comment by dcmr** [comment]
I want to return json result  after fire rules .Could you paste a example? thanks a lot

**Comment by benas** [comment]
Even though this is a great idea, there is no plan to implement it in Easy Rules for now. I would be happy to add a reference to any contribution in the readme.
