### ISSUE TITLE
disable logging in version 3.2.0

### ISSUE THREAD

**Issue by mr0815mr** [j-easy/easy-rules#166]
Hi

a lot of people dont want your logging - you changed that in different ways für different versions of easy-rules. whats the way for 3.2.0

thanks mat

**Comment by benas** [comment]
Hi,

Easy Rules now uses SLF4J. Most of the logs will be turned into `debug` instead of `info`. This is planned for v3.2.

**Comment by benas** [comment]
Looks like I missed this for v3.2.

I [changed](https://github.com/j-easy/easy-rules/commit/d2fed7be7625227e04a537f434316ad9bccec855) the default log level to `debug`. This will be part of the upcoming v3.3 release.
