### ISSUE TITLE
Facing performance issue

### ISSUE THREAD

**Issue by ramnaresh2051** [j-easy/easy-rules#169]
I am facing a performance issue with RuleEngine. If no of threads/requests or  no of rules are more the performance goes down, I have wrote a below sample code, please check and let me know if I miss anything.
This works fine for 10 rules and 10 requests its give result in less than 50ms.

```
import java.util.concurrent.ArrayBlockingQueue;
import java.util.concurrent.ThreadPoolExecutor;
import java.util.concurrent.TimeUnit;

import org.jeasy.rules.api.Facts;
import org.jeasy.rules.api.Rule;
import org.jeasy.rules.api.Rules;
import org.jeasy.rules.api.RulesEngine;
import org.jeasy.rules.core.DefaultRulesEngine;
import org.jeasy.rules.core.RuleBuilder;

public class RuleEnginePerfTest {
    
    private static Rules RULES_1 = new Rules();
    private static int NO_OF_REQUESTS = 50;
    private static int NO_OF_RULES = 50;
    private static RulesEngine ruleEngine;
    
    public static void main(String[] args) {
        ruleEngine = new DefaultRulesEngine();
        loadRules();
        fireRules();
    }

    private static void fireRules() {
        ThreadPoolExecutor executor = new ThreadPoolExecutor(100, 200, 100, TimeUnit.SECONDS, new ArrayBlockingQueue<>(100));
        Facts facts = new Facts();
        
        facts.put("proxyUrl", "easy/v7/api");
        ruleEngine.fire(RULES_1, facts);
        
        for (int i = 0; i < NO_OF_REQUESTS; i++) {
            Wokrer worker1 = new Wokrer(ruleEngine, RULES_1, facts);
            executor.submit(worker1);
        }
        executor.shutdown();
        System.out.println("Finished all threads");
    }

    private static void loadRules() {
        for (int i = 0; i < NO_OF_RULES; i++) {
            String condtion = "easy/v"+i+"/api";
            String action = "Execute for rule" + i;
            Rule rule = new RuleBuilder()
                        .name("weather rule" + i)
                        .priority(NO_OF_RULES - i)
                        .description("if it rains then take an umbrella")
                        .when(facts -> facts.get("proxyUrl").equals(condtion))
                        .then(facts -> System.out.println(action))
                        .build();
            RULES_1.register(rule);
        }
    }

}


class Wokrer implements Runnable {
    
    RulesEngine ruleEngine;
    Rules rules;
    Facts facts;
    
    public Wokrer(RulesEngine ruleEngine, Rules rules, Facts facts) {
        this.ruleEngine = ruleEngine;
        this.rules = rules;
        this.facts = facts;
    }

    @Override
    public void run() {
        long startTime = System.currentTimeMillis();
        ruleEngine.fire(rules, facts);
        System.out.println("Time Taken in ms:"+ (System.currentTimeMillis()-startTime));
    }
    
}
```

**Comment by ramnaresh2051** [comment]
can you please update on this.

**Comment by benas** [comment]
Hi,

A couple of notes:

* What is your baseline here? How can you confirm there is a performance issue (compared to what)?
* Please update your benchmark using [JMH](http://openjdk.java.net/projects/code-tools/jmh/) (or a similar tool). Consider having a throughput bench rather than time based bench.
* Your example is not the best setup for a performance bench: Each worker has its own rules engine instance, rules set instance and facts instance. The rules engine and the rules can be shared between threads (algorithm), the facts (data) should be per thread.

Kr,
Mahmoud

**Comment by ramnaresh2051** [comment]
@benas 
Thanks for update ... In my code I am using as you have mentioned. And I was trying to check performance using Jmeter. I have noticed that there is no issue in rule engine once I set log level in **error** mode. This seems to be an issue while logging, threads are getting blocked. I am investing this from my side, I will get back to you in case logs are blocked due to engine code. 

attaching thread dump once logs are enabled.
[dump_file.txt](https://github.com/j-easy/easy-rules/files/2212615/dump_file.txt)

**Comment by cemo** [comment]
We had some similar issues. Disable logging. Listeners of j-easy is printing INFO level logs. These are massive in our side and caused some contention on our OutputStream. Try to disable it and compare it again. 

@benas Hi again, I had

**Comment by benas** [comment]
I changed the default log level to debug (See #166). The fix has been published in v3.3.0-SNAPSHOT. Can you please try with this version and let me know if you still have the performance issue?

Thank you upfront!

**Comment by benas** [comment]
Any update on this?

Now that Easy Rules uses SLF4J and all log messages have been changed to `debug` level by default, I think the performance issue should be fixed. Obviously, the choice of the underlying logging framework is important. From my experience, the combo SLF4J + Logback with an `AsyncAppender` gives optimum performance.

**Comment by benas** [comment]
Now that logging is based on slf4j (See #113) and that the default log level has been changed to DEBUG (In #166), I think the performance issue should be solved. Otherwise we can blame slf4j (and/or the underlying logging framework) 🙃 

I'm closing this issue for now, but feel free to re-open it if you still have the performance problem with the upcoming v3.3.
