### ISSUE TITLE
Custom operators

### ISSUE THREAD

**Issue by selekt** [j-easy/easy-rules#172]
Hi, 

I am reviewing various rules engine for my project. One of the requirements that we have is to be able to write our own geographical operators. For example, I want our customers to be able to define something like : "$city in_state OR" ... so if $city => "Portland" .. this should return true and false for cities that don't exist in OR state. There are internal services we can use to determine geographical locations. My question is - how easy would it be to extend EasyRules to support use cases like these? ... this is one example, but there are many others like this we would like to support. 

Thank you for your time.

**Comment by selekt** [comment]
Hi - ping to bump this up.

**Comment by benas** [comment]
> how easy would it be to extend EasyRules to support use cases like these?

rules in easy rules are expected to be written in Java. If you want to support another language or syntax, it is as easy as implementing the `Rule` interface to support the syntax (`MVELRule` is one example).
