### ISSUE TITLE
use in Android - 

### ISSUE THREAD

**Issue by sankar07** [j-easy/easy-rules#173]
Hai, 

How can I use this library in android ?

**Comment by gauravpolekar** [comment]
You can add gradle dependency and use directly in android project.

// https://mvnrepository.com/artifact/org.jeasy/easy-rules-core
compile group: 'org.jeasy', name: 'easy-rules-core', version: '3.0.0'

**Comment by benas** [comment]
Easy Rules can be used with android like any other library. You just need to import it as shown by @gauravpolekar 

@gauravpolekar That you for the follow up!
