### ISSUE TITLE
Is there a way to have multiple conditional statement in yml condition

### ISSUE THREAD

**Issue by ruchichhabra009** [j-easy/easy-rules#182]
Hi,

I am looking for running multiple conditions in Yml file:
title != null; title.length < 255;

Please update if something like this can be done.

**Comment by ruchichhabra009** [comment]
Can I use somthing like this @benas 
condition: 153573467 > Instant.now().toEpochMilli()
Please update.

**Comment by benas** [comment]
> Is there a way to have multiple conditional statement in yml condition

Yes, the condition can be as complex as you want, as long as it is a correct MVEL condition.

> Can I use somthing like this @benas
> condition: 153573467 > Instant.now().toEpochMilli()

That's rather an MVEL question 😄 I would add a fact named `now `with the value of `Instant.now().toEpochMilli()` and then use it in the condition like `153573467 > now`.

I'm closing this issue but you can comment here if you want.
