### ISSUE TITLE
ActivationRuleGroup has NullPointerException

### ISSUE THREAD

**Issue by ruanjiehui** [j-easy/easy-rules#183]
Hey everyone
When I use easy-rules-support 3.2.0,I found a bug in ActivationRuleGroup.The following is the details:
1. Version:3.2.0
2. Class:`org.jeasy.rules.support.ActivationRuleGroup`
3. Problem: When I direct call `ActivationRuleGroup.execute()` method,it will throw `NullPointerException`.Because `selectedRule` is `null`.

**Comment by benas** [comment]
Fixed by merging #184
