### ISSUE TITLE
Remove item from facts in actions (then)

### ISSUE THREAD

**Issue by mail2niaz** [j-easy/easy-rules#185]
Assume I had facts {name: niaz, age : 3} which I want to remove age attribute when "when" condition is true. I know I can add/modify facts but don't find a way to remove an attribute. pl guide. btw this library is excellent 👌

**Comment by benas** [comment]
Hi,

To remove a fact, you can use [`Facts#remove`](http://static.javadoc.io/org.jeasy/easy-rules-core/3.2.0/org/jeasy/rules/api/Facts.html#remove-java.lang.String-) method.

> btw this library is excellent 👌

Thank you! Glad you like it!

Kr,
Mahmoud.
