### ISSUE TITLE
Unsupported major.minor version 51.0 or  52.0

### ISSUE THREAD

**Issue by Imatvoid** [j-easy/easy-rules#186]
I know that's because I use JDK 6 in local environment,  but I can't change that. so  I can only  use easyrules 1.3.0 ？

**Comment by atVoidYX** [comment]
Sorry, there are some mistakes in my previous description.
What I want to ask is:
 Can I compile easyrules 2.4.0 source package to jar with JDK 6 ?
I corrected some grammatical problems with  2.4.0 source package in the JDK 6 environment，
but I don't know if there will be any other problems.

**Comment by benas** [comment]
> Can I compile easyrules 2.4.0 source package to jar with JDK 6 ?

You can always try to compile it against JDK 6. However, I'm not sure it will work, Easy Rules 2.x requires Java 7+.

I'm closing this issue for now, but you can add any comment/concern here.
