### ISSUE TITLE
Modify private access of HashMap in org.jeasy.rules.api.Facts to protected

### ISSUE THREAD

**Issue by magnublo** [j-easy/easy-rules#187]
Could the line `private Map<String, Object> facts = new HashMap<>();` in `org.jeasy.rules.api.Facts` be modified to give protected access? I have a situation where I want to make the `Facts` class less permissive and override the `put` and `get` methods to accept `enum` instead of `String`.

**Comment by benas** [comment]
I'm not sure you can override `put` and `get` to accept enum instead of String even if `facts` is changed to `protected`. Moreover, you can access the `facts` in your subclass using `Facts#asMap`. Here is an example:

```java
import java.util.Map;

public class LessPermissiveFacts extends Facts {

    @Override
    public Object put(String name, Object fact) { // it is not possible to change signature here to accept enum
        Map<String, Object> facts = super.asMap(); // you can access the facts with  super.asMap()
        // do something with facts
        return super.put(name, fact);
    }

    @Override
    public <T> T get(String name) { // it is not possible to change signature here to accept enum
        Map<String, Object> facts = super.asMap(); // you can access the facts with  super.asMap()
        // do something with facts
        return super.get(name);
    }
}
```

Does this make sense?

**Comment by benas** [comment]
@ magnublo based on your "thumbs up" reaction on my previous comment, I believe I can close this issue. Feel free to add a comment here if you still need help.
