### ISSUE TITLE
Need support of throwing exception in actions

### ISSUE THREAD

**Issue by rroshan91** [j-easy/easy-rules#190]
Hi,

I am trying to do "throw new Exception(\"Not supported\");" in actions but I am getting below error:

[Error: unresolvable property or identifier: throw]
[Near : {... throw new Exception("Not ....}]
^
[Line: 1, Column: 1]

**Comment by benas** [comment]
That's specific to MVEL, not Easy Rules. From [MVEL docs](http://mvel.documentnode.com), I don't see any way to throw an exception from an expression. So I'm afraid, Easy Rules can do nothing to support it.
