### ISSUE TITLE
Rules of Continuous Execution

### ISSUE THREAD

**Issue by panqingcui** [j-easy/easy-rules#191]
Rules of Continuous Execution

After the first rule is executed, the second rule relies on the first rule data for execution.

**Comment by tsafo** [comment]
See the demo in java package org.jeasy.rules.tutorials.shop of easy-rules-tutorials project.

**Comment by benas** [comment]
@panqingcui Thank you for opening this issue. But I don't understand it. Is it a question? Or you think there is  bug in Easy Rules?

Please elaborate and I will try help.

NB: I'm closing this issue for now but please do not hesitate to add your questions/comments here.
