### ISSUE TITLE
Logging level needs to be improved

### ISSUE THREAD

**Issue by jajupreetam** [j-easy/easy-rules#192]
Once I import the jar into my project, all the logs are produced at INFO level, can you please change this accordingly so that my application doenst produces too much of logs.

eg-

18:50:07.874 [main] INFO org.jeasy.rules.core.DefaultRulesEngineListener - Engine parameters { skipOnFirstAppliedRule = false, skipOnFirstNonTriggeredRule = false, skipOnFirstFailedRule = false, priorityThreshold = 2147483647 }
18:50:07.881 [main] INFO org.jeasy.rules.core.DefaultRulesEngineListener - Registered rules:
18:50:07.891 [main] INFO org.jeasy.rules.core.DefaultRulesEngineListener - Rule { name = 'firstname rule', description = 'firstName should not be empty/blank', priority = '2147483646'}
18:50:07.893 [main] INFO org.jeasy.rules.core.DefaultRulesEngineListener - Rule { name = 'lastname rule', description = 'lastname should not be empty/blank', priority = '2147483646'}
18:50:07.893 [main] INFO org.jeasy.rules.core.DefaultRulesEngineListener - Known facts:
18:50:07.893 [main] INFO org.jeasy.rules.core.DefaultRulesEngineListener - Fact { myRowData : jeasyrule.MyRowData@27ddd392 }
18:50:07.893 [main] INFO org.jeasy.rules.core.DefaultRulesEngineListener - Rules evaluation started
beforeEvaluate firstname rule
18:50:07.905 [main] INFO org.jeasy.rules.core.DefaultRuleListener - Rule 'firstname rule' triggered
afterEvaluate firstname rule evaluationResult true
beforeExecute firstname rule
FirstName Valid:true
18:50:07.906 [main] INFO org.jeasy.rules.core.DefaultRuleListener - Rule 'firstname rule' performed successfully
onSuccess firstname rule
beforeEvaluate lastname rule
18:50:07.906 [main] INFO org.jeasy.rules.core.DefaultRuleListener - Rule 'lastname rule' has been evaluated to false, it has not been executed
afterEvaluate lastname rule evaluationResult false

**Comment by benas** [comment]
This is fixed in #166. Please keep tuned for v3.3.
