### ISSUE TITLE
Multiple conditions in yaml file

### ISSUE THREAD

**Issue by joerkent** [j-easy/easy-rules#193]
Can you have multiple conditions in the yaml file similar to actions?

conditions:
   - "condition_one"
   - "condition_two"

**Comment by benas** [comment]
how would easy rules interpret this? 

* condition_one *or* condition_two

or

* condition_one *and* condition_two

So as you can see, that's not possible. You have to specify only one condition and combine sub conditions as you need. for example:

- condition: "condition_one xor condition_two"

**Comment by joerkent** [comment]
That is exactly what I needed, Thank you.
