### ISSUE TITLE
Question: any way to put the Fact value from application properties

### ISSUE THREAD

**Issue by AlexanderTorchynskyi** [j-easy/easy-rules#195]
Hey all, thanks for the awesome lib, I'm currently looking for a way where I could put the value for a `@Fact` from application properties:
```
   @Condition
    public boolean someTest(@Fact(value = "${test.prop}") String test) {
    // Some condition 
}
```
In the case as I write above the fact value will be `"${test.prop}` but not the actual value from `application.properties`
Is  there any way how I can do that? 
Thanks

**Comment by benas** [comment]
Easy Rules does not perform any property resolution. I guess you are referring to Spring (Boot). What you can do it something like:

```java
@Component
public class MyRule {

    @Value("${test.prop}")
    private String test;

    @Condition
    public boolean someTest(Facts facts) {
        facts.put("test", this.test);
        // some condition
    }
}
```

you inject the property in a field of your class using `@Value` and then add it to your facts.

Is this what you are looking for?

NB: I'm closing this issue but you can answer/comment as needed.

**Comment by AlexanderTorchynskyi** [comment]
> Easy Rules does not perform any property resolution. I guess you are referring to Spring (Boot). What you can do it something like:
> 
> ```java
> @Component
> public class MyRule {
> 
>     @Value("${test.prop}")
>     private String test;
> 
>     @Condition
>     public boolean someTest(Facts facts) {
>         facts.put("test", this.test);
>         // some condition
>     }
> }
> ```
> 
> you inject the property in a field of your class using `@Value` and then add it to your facts.
> 
> Is this what you are looking for?
> 
> NB: I'm closing this issue but you can answer/comment as needed.

Hey  @benas thanks for the reply, the idea of the `@Value` thing is keeping all fact name in the same place in my case that was `application.properties`, so facts are not hardcoded and once somebody changed a fact name in on of dozen rules it wouldn't work everywhere not just in one place.
