### ISSUE TITLE
Add support for parser context in MVEL conditions/actions

### ISSUE THREAD

**Issue by wuhaidu** [j-easy/easy-rules#197]
MVEL provides the ability to programmatically import individual classes, entire packages, and even static methods,But I didn't find this capability in easy-rule, and I couldn't extend MVELAction to execute it.
Mvel:

```java
ParserContext ctx = new ParserContext（）;
ctx.addPackageImport（“java.util”）; //import java.util.*
Serializable s = MVEL.compileExpression（expression，ctx）;
```

This is the only way in easy-rule:

```java
compiledExpression = MVEL.compileExpression(expression);
```

**Comment by benas** [comment]
Hi @wuhaidu 

Thank you for reporting this issue! I added a constructor to `MVELAction` that accepts a parser context. You can see an example [here](https://github.com/j-easy/easy-rules/blob/master/easy-rules-mvel/src/test/java/org/jeasy/rules/mvel/MVELActionTest.java#L89-L103). This will be part of the upcoming v3.3. Stay tuned.

Kr,
Mahmoud

**Comment by wuhaidu** [comment]
First of all, thank you for answering my questions. Now I can import external classes to execute the rules, but some of them are difficult to implement.
Actions in the rule set generated using MVELRuleFactory's createRulesFrom () method can't use the constructor you added to MVELAction, which is troublesome, and the class modifier of MVELRuleDefinitionReader and MVELRuleDefinition is the default level, which means that I can't extend or use MVELRuleDefinitionReader and MVELRuleDefinition from other packages, and it's not clear for the time being what you are for. Reasons limit his expansion.I'm a little lazy and don't repeat wheels. I think it's best to expand.
`Rules rules = MVELRuleFactory.createRulesFrom(new FileReader(file.toFile()));`
I would like to add a method that can be used to your constructor, as follows:
```
ParserContext context = new ParserContext();
            context.addPackageImport("java.util");
            //
            File file = new File("testRule.yml");
            Rules rules = MVELRuleFactory.createRulesFrom(new FileReader(file), context);
```
MVELRuleFactory should have such a method:
```
...
public static Rules createRulesFrom(Reader rulesDescriptor, ParserContext context) {
        Rules rules = new Rules();
        List<MVELRuleDefinition> ruleDefinition = reader.readAll(rulesDescriptor);
        for (MVELRuleDefinition mvelRuleDefinition : ruleDefinition) {
            rules.register(mvelRuleDefinition.createSimpleRule(context));
        }
        return rules;
    }
...
```
Finally, this is the more reasonable test method I imagine.
```
...
@Test
    public void testParseContext(){
        try {
            ParserContext context = new ParserContext();
            context.addPackageImport("java.util");
            //
            File file = new File("testRule.yml");
            Rules rules = MVELRuleFactory.createRulesFrom(new FileReader(file), context);
            RulesEngine rulesEngine = new DefaultRulesEngine();

            //
            Facts facts = new Facts();
            rulesEngine.fire(rules, facts);
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }
    }
...
```

**Comment by benas** [comment]
@wuhaidu Thank you for your great feedback! It looks like I closed this issue too early.. I have added two things:

* The ability to use a parser context in conditions (in addition to actions). See c83ff59da8e35c96a0bdcab45db21471b9ed32d4
* The ability to create a rule from a file with a parser context as you suggested. See 3f6e87b2028055339929326333b588d3b21709eb

Now it is possbile to do something like:

```java
ParserContext context = new ParserContext();
context.addPackageImport("java.util");
File file = new File("testRule.yml"); // both conditions and actions can use "java.util" classes thanks to the parser context
Rules rules = MVELRuleFactory.createRulesFrom(new FileReader(file), context);
```

I pushed these additions in the latest snapshot version. Could you give it a try and let me know if this is ok for you? Please check [this page](https://github.com/j-easy/easy-rules/wiki/getting-started#use-a-snapshot-version) if you don't know how to import the snapshot version.

Thank you upfront!

**Comment by wuhaidu** [comment]
Thank you very much for your reply. I tried these new features in the snapshot version. It's good. Easy-rule is more flexible. If there are any other questions, I will come to ask you. Thank you. I look forward to v3.3.

**Comment by wuhaidu** [comment]
> Thank you very much for your reply. I tried these new features in the snapshot version. It's good. Easy-rule is more flexible. If there are any other questions, I will come to ask you. Thank you. I look forward to v3.3.
> my test:
> 
> ```
> try {
>             ParserContext context = new ParserContext();
>             context.addPackageImport("java.util");
>             context.addPackageImport("utry.robot.base.runtime");
>             context.addImport(RobotPlatformConnectionState.class);
> 
>             //
>             File file = new File("config/weather-rule.yml");
>             Rules rules = MVELRuleFactory.createRulesFrom(new FileReader(file), context);
>             RulesEngine rulesEngine = new DefaultRulesEngine();
> 
>             //
>             Facts facts = new Facts();
>             rulesEngine.fire(rules, facts);
>         } catch (Exception e) {
>             e.printStackTrace();
>         }
> ```
> Gradle 配置:
> 
> ```
> ...
> maven {
> 		name 'ossrh'
> 		url 'https://oss.sonatype.org/content/repositories/snapshots'
> 	}
> ...
> compile('org.jeasy:easy-rules-mvel:3.3.0-SNAPSHOT'){
> 		exclude group: "org.slf4j"
> 	}
> ...
> ```

**Comment by wuhaidu** [comment]
> > Thank you very much for your reply. I tried these new features in the snapshot version. It's good. Easy-rule is more flexible. If there are any other questions, I will come to ask you. Thank you. I look forward to v3.3.
> > my test:
> > ```
> > try {
> >             ParserContext context = new ParserContext();
> >             context.addPackageImport("java.util");
> >             context.addPackageImport("utry.robot.base.runtime");
> >             context.addImport(RobotPlatformConnectionState.class);
> > 
> >             //
> >             File file = new File("config/weather-rule.yml");
> >             Rules rules = MVELRuleFactory.createRulesFrom(new FileReader(file), context);
> >             RulesEngine rulesEngine = new DefaultRulesEngine();
> > 
> >             //
> >             Facts facts = new Facts();
> >             rulesEngine.fire(rules, facts);
> >         } catch (Exception e) {
> >             e.printStackTrace();
> >         }
> > ```

**Comment by benas** [comment]
> I tried these new features in the snapshot version. It's good

Great! Thank you for taking time to test the fix!
