### ISSUE TITLE
Is there any way to print/log condition and action 

### ISSUE THREAD

**Issue by ramnaresh2051** [j-easy/easy-rules#199]
For a rule we can print rule name, priority and description but is there any way to print/log condition and action.

**Comment by benas** [comment]
I'm not sure I understand your question. What do you mean by "is there any way to print/log condition and action"? You can add log in your rule's condition/action methods, do you agree?

**Comment by benas** [comment]
I'm closing this issue for now. Please elaborate on your question and I will answer in comments.
