### ISSUE TITLE
ConditionalRuleGroup has wrong priority control

### ISSUE THREAD

**Issue by Jeff-Jia** [j-easy/easy-rules#203]
Normally, lower values represent higher priorities. But in ConditionalRuleGroup, higher values represent higher priorities. I think here has some bugs when you sort the Rule List. Could you please fix this issue?

Thanks.
B.R.

**Comment by benas** [comment]
Thank you for reporting this issue! Indeed that's a bug in `ConditionalRuleGroup`. I will fix that asap and include it in the upcoming v3.3

**Comment by benas** [comment]
@Jeff-Jia I deployed a fix in [v3.3.0-SNAPSHOT](https://github.com/j-easy/easy-rules/wiki/getting-started#use-a-snapshot-version), can you give it a try and let me know if it is ok for you?

**Comment by Jeff-Jia** [comment]
> @Jeff-Jia I deployed a fix in [v3.3.0-SNAPSHOT](https://github.com/j-easy/easy-rules/wiki/getting-started#use-a-snapshot-version), can you give it a try and let me know if it is ok for you?

Hi, I checked your commit and test with the new code, the bug already fixed, thank you very much~~

**Comment by benas** [comment]
Great! Thank you for raising the issue and for testing the fix!
