### ISSUE TITLE
Is there a release plan for 3.3.0 ?

### ISSUE THREAD

**Issue by yrjyrj123** [j-easy/easy-rules#205]
This is a very useful project and I used it in our production system.
Recently I found a new version 3.3.0-SNAPSHOT, added SPEL support and a lot of new features.

It's great !

We hope to use this new version.
Do you have more features you want to join? We are willing to help you develop together.
Make the snapshot become release as soon as possible.

Thank you

**Comment by benas** [comment]
Awesome! Glad to hear that 👍 v3.3 is planned for April 28.

> Do you have more features you want to join?

No, v3.3 is feature complete by now. I'm taking a couple weeks to fix bugs, polish the code/docs then release it.

> We are willing to help you develop together.

Sure! You are welcome. Can you please try the newly added SpEL support and give me your feedback? I would be grateful. Thank you upfront!
