### ISSUE TITLE
Register Rules Once On App Start In Spring Boot Application

### ISSUE THREAD

**Issue by felahi** [j-easy/easy-rules#207]
Is there any way to register all the rules on the App start and fire them when required. Currently, on every API call, I have to register the same rules again and again.

**Comment by benas** [comment]
we used to have a spring boot starter for easy rules in v2 (#65) but Spring support has been discontinued in v3 (see details in #74 ).

> Is there any way to register all the rules on the App start and fire them when required.

There is no built-in way to do this, you need to do it manually. You can use a listener for `ApplicationReadyEvent` or simply add a `ApplicationRunner` and register your rules once there. This [SO thread](https://stackoverflow.com/questions/27405713/running-code-after-spring-boot-starts) may help.

I'm closing this issue for now, but please don't hesitate to comment here if you need help.
