### ISSUE TITLE
Set Value after successful rule execution

### ISSUE THREAD

**Issue by felahi** [j-easy/easy-rules#208]
On successful execution of a rule, I want to set some info in the field.

**Comment by benas** [comment]
You can use a [`RuleListener#onSuccess`](https://github.com/j-easy/easy-rules/wiki/defining-rules-listener) and set the field in that method.

**Comment by felahi** [comment]
But how do I access the object in RuleListener in which I need to set a value?

**Comment by benas** [comment]
A rule's action can create/delete/modify facts, and the set of facts is accessible in `RuleListener#onSuccess` method. So you can use your object as a fact to get access to it and modify it as needed after the rule execution.
