### ISSUE TITLE
How can I create an instance of a customize class？

### ISSUE THREAD

**Issue by Jeff-Jia** [j-easy/easy-rules#209]
Hello benas:
    I have a question about create instance.
    For example, there is a customize class named "Apple", and here is a static function named "getAppleCount()". I write below source code:

    Facts facts = new Facts();
    facts.put("Apple", Apple.class);

    And then, in yml file, I write down actions like this:

    - "Apple apple = new Apple();"  ------  AnroidRuntime: unknown class or illegal statement
    - "Apple.getAppleCount();"  ----- OK

    I don't know why, could you please give me some suggestion about how to create an instance of Apple class?

Thank you very much.
Best Regards and Wishes!

**Comment by Jeff-Jia** [comment]
Hello benas:
    I find that, if I write down the hole package of "Apple", it is worked.
    But I met another one...
    I add a static function in class "Apple", it named "getAppleList()".
    In this function, I print something, and return a ArrayList<String>.
    I hope I can get the list in my yml file.
    In yml file, I write down below code.

- "Apple.getAppleList();"  ------  OK, print log successfully
- "List<String> strList = null;"  ------  Error: unresolvable property or identifier: List
- "java.util.List<String> strList = null;"  ------  OK
- "String str = Apple.getString();"  ------  OK, can get the return value successfully
- "java.util.List<String> strList = Apple.getAppleList();"  ------  org.mvel2.ConversionException: cannot convert type: java.util.ArrayList to: java.lang.Boolean

    It show, we can get the String as a return value, but ArrayList<String> failed.

    So, could you please give me any suggestion how can I get the ArrayList<String> as a return value?

Thank you very much.
Best Regards and Wishes!

**Comment by zhhaojie** [comment]
> * mvel2
may be you can do it like this .
` // given
        ParserContext context = new ParserContext();
        context.addPackageImport("java.util");
`

**Comment by Jeff-Jia** [comment]
> may be you can do it like this .
> 
> `ParserContext context = new ParserContext(); context.addPackageImport("java.util");`

我本来在上面的comment里写个泛型，List里装String类型的变量，但是Github好像显示不出来......
写了泛型，赋值操作的时候就会发生问题。最后发现是因为MVEL不支持那么写

**Comment by benas** [comment]
> * So, could you please give me any suggestion how can I get the ArrayList as a return value?

MVEL [supports variable assignment](http://mvel.documentnode.com/#assignments), so that should not be an issue. However, there are two ways of using your "Apple" class:

#### 1. Using `ParserContext`:

The `ParserContext` allows you to import individual classes or all classes from a given package so you don't have to specify the fully qualified class name in your MVEL expressions. Here is an example with your "Apple" class:

```java
package org.jeasy.rules.mvel;

import org.jeasy.rules.api.Action;
import org.jeasy.rules.api.Facts;
import org.mvel2.ParserContext;

import java.util.Arrays;
import java.util.List;

public class Apple {

    public static String getApple() {
        return "apple";
    }

    public static List<String> getApples() {
        return Arrays.asList("apple1", "apple2");
    }

    public static void main(String[] args) throws Exception {
        ParserContext context = new ParserContext();
        context.addImport(Apple.class); // or use context.addPackageImport("org.jeasy.rules.mvel"); to import all classes from org.jeasy.rules.mvel
        context.addImport(List.class); // or use context.addPackageImport("java.util"); to import all classes from java.util

        // example of String assignment
        Action action1 = new MVELAction("String str = Apple.getApple(); System.out.println(str);", context);
        action1.execute(new Facts());

        // example of List assignment
        Action action2 = new MVELAction("List apples = Apple.getApples(); System.out.println(apples);", context);
        action2.execute(new Facts());
    }
}
```
this prints:

```
apple
[apple1, apple2]
```

which means both `String` and `List` assignment are correctly parsed.

#### 2. Without using `ParserContext`

If you don't want to use the `ParserContext`, you need to write the fully qualified class name in your MVEL expression. Here is an example:

```java
package org.jeasy.rules.mvel;

import org.jeasy.rules.api.Action;
import org.jeasy.rules.api.Facts;

import java.util.Arrays;
import java.util.List;

public class Apple {

    public static String getApple() {
        return "apple";
    }

    public static List<String> getApples() {
        return Arrays.asList("apple1", "apple2");
    }

    public static void main(String[] args) throws Exception {
        // example of String assignment
        Action action1 = new MVELAction(
                "String str = org.jeasy.rules.mvel.Apple.getApple();" +
                "System.out.println(str);"
        );
        action1.execute(new Facts());

        // example of List assignment
        Action action2 = new MVELAction(
                "java.util.List apples = org.jeasy.rules.mvel.Apple.getApples();" +
                        "System.out.println(apples);"
        );
        action2.execute(new Facts());
    }
}
```

This also prints:

```
apple
[apple1, apple2]
```

Hope this helps.

I'm closing this issue for now but please do not hesitate to add your questions/comments here.

@zhhaojie Thank you for the follow up!
