### ISSUE TITLE
I have a conditon like this "a in (a,b,c,d,e)",how do I use "in" in a conditon?

### ISSUE THREAD

**Issue by Keith-yunchen** [j-easy/easy-rules#212]
I have a conditon like this "a in (a,b,c,d,e)",how do I use "in" in a conditon?

**Comment by benas** [comment]
The nice things about easy rules is that rules are written in Java, so you can use any Java construct to implement the "in" operator.

Here is an example with a condition that checks if a fact is in a list of values:

```java
    static class Example {
        public static void main(String[] args) {
            @org.jeasy.rules.annotation.Rule
            class MyRule {
                
                @org.jeasy.rules.annotation.Condition
                public boolean condition(@Fact("value") String value) {
                    return Arrays.asList("a", "b", "c").contains(value);
                }
                
                @org.jeasy.rules.annotation.Action
                public void action() {
                    System.out.println("yes");
                }
            }

            RulesEngine engine = new DefaultRulesEngine();
            Facts facts = new Facts();
            facts.put("value", "a");
            Rules rules = new Rules();
            rules.register(new MyRule());
            engine.fire(rules, facts); // prints "yes"
        }
    }
```

**Comment by zhhaojie** [comment]
> I have a conditon like this "a in (a,b,c,d,e)",how do I use "in" in a conditon?

`
Facts facts = new Facts();
        facts.put("x","c");
        Condition containsCondition = new SpELCondition("{'a','b','c'}.contains(#x)");
        containsCondition.evaluate(facts);
        assertThat(containsCondition.evaluate(facts)).isTrue();
`
`
        Facts facts = new Facts();
        facts.put("x","c");
        Condition containsCondition = new MVELCondition("['a','b','c'] contains x ");
        containsCondition.evaluate(facts);
        assertThat(containsCondition.evaluate(facts)).isTrue();

`

**Comment by Keith-yunchen** [comment]
3ks,actually the value in array was in the mysql,but I think i have some idea to solve this.
