### ISSUE TITLE
composite rules

### ISSUE THREAD

**Issue by pallavialuri** [j-easy/easy-rules#219]
Hi

I am trying to implement composite rule...so heres the use case...i have main condition which checks device type and after it checks device types depending on the return value of one of the methods there are different types of actions to be implemented..could you please provide help on how to implement..

attaching files for review.

thank you in advance
[composite rule.zip](https://github.com/j-easy/easy-rules/files/3397923/composite.rule.zip)

**Comment by benas** [comment]
> i have main condition which checks device type and after it checks device types depending on the return value of one of the methods there are different types of actions to be implemented

You need multiple rules for your use case. An example can be found here: https://stackoverflow.com/a/58029884/5019386
