### ISSUE TITLE
composite rule

### ISSUE THREAD

**Issue by pallavialuri** [j-easy/easy-rules#220]
Hi I am trying to implement composite rules. But its not working for me. I am implementing through  json file . This is the code i am using to read the file and fire the rules.

  MVELRuleFactory factory = new MVELRuleFactory(new JsonRuleDefinitionReader());
        Rules orderRule = factory.createRules(new FileReader("C:\\Users\\PALURI1\\Downloads\\easy-rules-easy-rules-3.3.0\\easy-rules-easy-rules-3.3.0\\easy-rules-tutorials\\src\\main\\java\\org\\jeasy\\rules\\tutorials\\device\\order-rule.json"));

        RulesEngine rulesEngine = new DefaultRulesEngine();

        rulesEngine.fire(orderRule, facts);

But still its not giving the proper result for the rule .

My use case is i have a condition on which i need to validate the rule. Then after the condition is satisfied there different type of actions to be implemented depending upon the return value of a method.

Could you please help me in sorting this out and implement. Thank you in advance.

Attaching the files for review
[composite rule.zip](https://github.com/j-easy/easy-rules/files/3402156/composite.rule.zip)

**Comment by pallavialuri** [comment]
Also i would also like to know whether we can implement more than one condition in rule configuration file. Thank you in advance

**Comment by pallavialuri** [comment]
@benas  could you please provide help regarding the implementation..

**Comment by zhhaojie** [comment]
there are something wrongs in `order-rule.json`.
when using `UnitRuleGroup`,all you rules in `composingRules` should ALL evaluate to true .
in your case, rule1 always evaluate to true ,rule2 always evaluate to false.

**Comment by pallavialuri** [comment]
hi @zhhaojie 
thank you for the response... could you please suggest how to implement my use case using easy rules. Should i be using othter type of composite rule instead of unit rule group or is there any other way.
Thank  you

**Comment by zhhaojie** [comment]
> hi @zhhaojie
> thank you for the response... could you please suggest how to implement my use case using easy rules. Should i be using othter type of composite rule instead of unit rule group or is there any other way.
> Thank you

sorry for late .

i review your case , the logic is simple, just like 
`
//rule group 
if(type =='TCU'){
   if(x){ do xx };
   if(y){ do yy };
}

//rule2
if(type == 'EPID'){
   if(z){ do zz };
}
`
you can simply to implements like 
`
//rule1
if(type == 'TCU' && x ){
    do xx; 
}
//rule2
if(type == 'TCU' && y ){
    do yy ; 
}
//rule3
if(type == 'EPID'){
   if(z){ do zz };
}
`

**Comment by zhhaojie** [comment]
> hi @zhhaojie
> thank you for the response... could you please suggest how to implement my use case using easy rules. Should i be using othter type of composite rule instead of unit rule group or is there any other way.
> Thank you

```
[
  {
    "name": "tcu rule",
    "compositeRuleType": "UnitRuleGroup",
    "priority": 1,
    "condition" : "type =='TCU'",
    "composingRules": [
      {
        "name": "rule1 ",
        "description": "if the flag is true",
        "priority": 2,
        "condition": "aRestAdapter.method1() == true",//attention here 
        "actions": [
          "cRestAdapter.method3(); dRestAdapter.method4(5)"
        ]
      },
      {
        "name": "rule2",
        "description": "if the flag is false",
        "priority": 2,
        "condition": "bRestAdapter.method2() == true",  //attention here 
        "actions": [
          "dRestAdapter.method4(5);"
        ]
      }
    ]
  },
  {
    "name": "epid",
    "description": "device type is epid",
    "priority": 1,
    "condition": "type == 'EPID'",
    "actions": [
      "cRestAdapter.method3();dRestAdapter.method4(5)"
    ]
  }
]
```
the final logic is 
if (type =='TCU' && aRestAdapter.method1() == true && bRestAdapter.method2() == true ){
 //rule1 
   "cRestAdapter.method3(); dRestAdapter.method4(5)"
//rule2
  "dRestAdapter.method4(5);"
}

aRestAdapter.method1() && bRestAdapter.method2() must ALL eq true, the action will fire. or ,fire nothing .

**Comment by benas** [comment]
@pallavialuri As mentioned in #219 (please don't duplicate issues) , it is not a composite rule that you need, your use case actually requires multiple (independent) rules, one for each type.

@zhhaojie Thank you for the follow up!
