### ISSUE TITLE
RuleProxy can be speed up by caching reflective access

### ISSUE THREAD

**Issue by warmuuh** [j-easy/easy-rules#221]
On every evaluation, the RuleProxy re-scans the class and extracts the information such as `@Rule` annotation, @Condition-annotated method, @Action-annotated methods and @Fact-annotated parameters (as well as other "scans" for e.g. equal-methods etc).

This information can be cached in the RuleProxy so that the condition/evaluation of the rule can be heavily speed up. Also the RuleProxy could be a class implementing Rule instead of being an invocation-handler for the Rule-Interface?

**Comment by benas** [comment]
Thanks for opening this issue. I wonder if other frameworks (like Spring) do this kind of caching for object introspection. I'm not even sure this is an issue actually. Have you noticed/measured a performance issue related to that? What would the cache structure be? I'm open for a PR if it really adds value (that is measurable) without making the code complex.

> Also the RuleProxy could be a class implementing Rule instead of being an invocation-handler for the Rule-Interface?

Unless we give up creating JDK dynamic proxies for POJO annotated rules and use another method, I'm not sure how this is possible given that `Proxy.newProxyInstance` requires an `InvocationHandler`.

**Comment by warmuuh** [comment]
we did a benchmark to compare annotatedRules to rules built using the RuleBuilder and rules implemented by inheriting from Rule interface.

Benchmark | # calculations | us per op | Error (99.9%) | Speedup to AnnotatedRule
-- | -- | -- | -- | --
AnnotatedRule | 1 | 39.587243 | 4.693175 |  
AnnotatedRule | 10 | 189.24852 | 5.201169 |  
AnnotatedRule | 100 | 1768.229415 | 59.509519 |  
AnnotatedRule | 1000 | 18251.74417 | 635.137258 |  
AnnotatedRule | 10000 | 182274.3689 | 5568.573606 |  
BuilderRule | 1 | 1.288458 | 0.275125 | 30.72451
BuilderRule | 10 | 11.603057 | 0.433716 | 16.31023
BuilderRule | 100 | 104.690688 | 12.355355 | 16.89004
BuilderRule | 1000 | 1163.940765 | 108.311776 | 15.68099
BuilderRule | 10000 | 11382.82587 | 805.385054 | 16.0131
InheritedRule | 1 | 1.548204 | 2.64042 | 25.56978
InheritedRule | 10 | 11.487205 | 0.535666 | 16.47472
InheritedRule | 100 | 104.581064 | 4.443549 | 16.90774
InheritedRule | 1000 | 1295.13496 | 999.627979 | 14.09254
InheritedRule | 10000 | 11426.79072 | 1279.002009 | 15.95149

we then created a proxy for caching the reflective access: https://gist.github.com/warmuuh/1fd2e6ecfabe46bca6644d78b80301cb

i sadly dont have time to create a proper PR with bells&whistles, but maybe this helps you already

**Comment by benas** [comment]
Thank you for these details! The way you implemented the caching (custom rule + doing the reflective access only once at construction time) could work in a custom project where you are free to use this rule. However, this is not appropriate to include as is in the library (we can't ask users to use a given implementation to improve performance).

I added a simple cache that does the reflective access only once (during the first call) and re-uses the calculated info in subsequent calls (See 2e85745). My initial benchmark ([easy-rules-benchmarks.zip](https://github.com/j-easy/easy-rules/files/3860577/easy-rules-benchmarks.zip)) shows that we have 50% throughput improvement using this method:

```
v3.3.0

Benchmark                                                                Mode  Cnt   Score   Error   Units
ReflectionCachingBenchmark.performanceTestOfRuleProxyReflectionCaching  thrpt   10  57.960 ± 2.239  ops/ms

v3.4.0-SNAPSHOT

Benchmark                                                                Mode  Cnt    Score   Error   Units
ReflectionCachingBenchmark.performanceTestOfRuleProxyReflectionCaching  thrpt   10  102.991 ± 3.677  ops/ms
```

I deployed the change in v3.4.0-SNAPSHOT. Could you please give a try and share your feedback? (see [here](https://github.com/j-easy/easy-rules/wiki/getting-started#use-a-snapshot-version) if you don't know how to import the snapshot version). Many thanks upfront!

**Comment by warmuuh** [comment]
that looks promising, thanks for incorporating this change. I tested it and it does look better. One remark though: the caching is not perfect right now, some lookups which dont result in a default-value (such as "compareTo" method lookup) can end up in "null", if there is no such method. In that case, the lookup is done again unnecessarily (because null is used here to denote both absence of method and cache not initalized.). so this could be improved a little bit.

**Comment by benas** [comment]
yes I was aware of that, but I think it is a good start already. Let's iterate on that and improve the caching in another iteration. Contributions are welcome!

Thank you for opening the issue and taking time to test the change 👍
