### ISSUE TITLE
Remove DefaultRuleListener

### ISSUE THREAD

**Issue by liebig** [j-easy/easy-rules#223]
Thank you very much for this great library. I wanted to ask if it is possible to remove the DefaultRuleListener from the Rule Listener.

`DefaultRulesEngine rulesEngine = new DefaultRulesEngine(new RulesEngineParameters().skipOnFirstFailedRule(true));
rulesEngine.getRuleListeners().clear();` does not work.

Thank you
Marc

**Comment by benas** [comment]
> Thank you very much for this great library. 

Thank you! Glad you like it!

> rulesEngine.getRuleListeners().clear(); does not work.

This does not work because of #157 .

> I wanted to ask if it is possible to remove the DefaultRuleListener from the Rule Listener.

yes that's possible, it is not the first time someone asks to remove it (See #146). However, I wanted to know the motivation of this request. Can you please explain why do you want to remove it?

**Comment by benas** [comment]
ok, yet another time I see people removing default listeners: https://github.com/j-easy/easy-rules/issues/215#issuecomment-500710853. There should be a good reason (which I fail to see) for all these people to do that. 

So I will remove them in the next major release.

**Comment by liebig** [comment]
Hi benas,

Please excuse my late reply. Somehow I overlooked your query. We want to remove the DefaultRuleListener to define our own default listener. Here we would like to adjust the logging and also the logging format.

I am very pleased to hear that this will be possible from the next major release.

Thank you so much for your great work.

Many greetings from Germany
Marc

**Comment by pnewhook** [comment]
To clarify why we might want to remove the `DefaultRulesEngineListener`, I'm finding that at high volumes, logging in the DefaultRulesEngineListener is taking more time than actually evaluating the rules. Even when logging is set to WARN or ERROR, the call to `String.valueOf(fact.getValue())` is evaluated and relatively expensive. Thank you for removing it.

![DefaultRulesEngineListener Logging](https://user-images.githubusercontent.com/92876/81427809-4d03c200-9129-11ea-9765-0ce50429713b.png)
