### ISSUE TITLE
Rule extending from another rule

### ISSUE THREAD

**Issue by Ashishk80** [j-easy/easy-rules#224]
Is there a capability in EasyRule where conditional part of the rule can be extended from another rule

For example
AbstractRule1 When a=10
AbstractRule2  When b=20

I am calling it abstract rule because there is no action associated yet.

Rule3  When Rule1 AND Rule2 then return xyz

This way we can save same conditions in multiple rules, imagine where conditions are really complex and big one.

**Comment by isspek** [comment]
I am also interested in answer of this question. My additional question is how i can write nested rules where first rule is condition of second rule by using JSON rule expression.

**Comment by spoddar123** [comment]
I also want to know the answer of this question. I have two composite rules defined in my json with few subrules. How can i invoke composite rule 2 if the condition for first composite rules is true??/ Can anyone help me with that. thx

**Comment by spoddar123** [comment]
@benas could you please provide help regarding the implementation..

**Comment by benas** [comment]
@Ashishk80 If rules are written in Java, one can create an abstract class with the common condition, and subclass it for each rule that needs a specific condition. I would not call the abstract class a rule if it does not have an action.

@isspek 

> My additional question is how i can write nested rules where first rule is condition of second rule

This is possible by making the first rule adding a fact on which the second rule should be triggered.

@spoddar123 

> How can i invoke composite rule 2 if the condition for first composite rules is true??

**Comment by spoddar123** [comment]
@benas Thanks for replying, Below is my usecase. How can I invoke ALM Rule in this case if MCP rule is evaluated true.Thanks

{
		"name": "MCP Rule",
		"description": "Decision Making",
		"compositeRuleType": "ConditionalRuleGroup",
		"composingRules": [
			{
				"name": "SubRule1",
				"description": "if its usAccount == 123456 ,then return 123456",
				"condition": "mcpRule.getUsAccount() == 123456",
				"actions": [
					"mcpRule.setMcpResult(\"123456\");"
				]
			},
,
	{
		"name": "ALM Rule",
		"description": "Decision Making",
		"compositeRuleType": "ConditionalRuleGroup",
		"composingRules": [
			{
				"name": "SubRule1",
				"description": "if its usAccount == 123456 ,then return 123456",
				"priority": 0,
				"condition": "mcpRule.getUsAccount() == 123456",
				"actions": [
					"mcpRule.setMcpResult(\"123456\");"
				]
			},

**Comment by spoddar123** [comment]
Nevermind, I got it. thx

**Comment by benas** [comment]
I'm closing this issue for now, but you can add a comment if you need more help on this.

**Comment by spoddar123** [comment]
@benas 

Hi, I am still looking for an answer to my question.
{
"name": "MCP Rule",
"description": "Decision Making",
"compositeRuleType": "ConditionalRuleGroup",
"composingRules": [
{
"name": "SubRule1",
"description": "if its usAccount == 123456 ,then return 123456",
"condition": "mcpRule.getUsAccount() == 123456",
"actions": [
"mcpRule.setMcpResult("123456");"
]
},
,
{
"name": "ALM Rule",
"description": "Decision Making",
"compositeRuleType": "ConditionalRuleGroup",
"composingRules": [
{
"name": "SubRule1",
"description": "if its usAccount == 123456 ,then return 123456",
"priority": 0,
"condition": "mcpRule.getUsAccount() == 123456",
"actions": [
"mcpRule.setMcpResult("123456");"
]
},

How can I call ALM Rule when evaluation to MCP Rule is true in same json?
Thx
