### ISSUE TITLE
When will you plan to add easy-rule to Spring Project?

### ISSUE THREAD

**Issue by 61go** [j-easy/easy-rules#225]
I want to add easy-rule component to a Spring Project.
But i can't find way to do that.
W

**Comment by zhhaojie** [comment]
just treat easy rules engine as a simple class . 
just new an instance and call .
RulesEngine rulesEngine = new DefaultRulesEngine();

**Comment by benas** [comment]
We used to have Spring support in Easy Rules but this was deprecated (See #74).

As @zhhaojie mentioned, you can declare your rules and the rules engine as beans in your spring application and fire rules when needed.

@zhhaojie Thank you for the follow up!
