### ISSUE TITLE
Returning output of action from a rule

### ISSUE THREAD

**Issue by kanteshkm** [j-easy/easy-rules#226]
Hi,

we are planning to use easy-rule in our project, we need to return value from a rule, below is the example:

  _SpELRule ageRule = new SpELRule()
	                .name("Xpath rule")
	                .description("XPath condition")
	                .priority(1)
	                .when(" #xpath1 == 'test' && #xpath2 == '2' && #xpath3 == '3' ")
	                .then("#**person.getValue(#xpath1)**");_

in the above  rule,  action will return a value [person.getValue()] and i need to return the value as response [it will be rest api, stateless]

is it possible to do return a value from matching rule?

thanks
Kantesh

**Comment by benas** [comment]
Please check [Q2 in the FAQs section](https://github.com/j-easy/easy-rules/wiki/faqs#2-i-would-like-to-return-a-value-upon-a-rule-execution-how-to-do-that). Basically your rule should add a fact, then you can query the `Facts` object after rule execution to get the result.
