### ISSUE TITLE
 When using YML file to write code, it is difficult to check the exceptional errors

### ISSUE THREAD

**Issue by wuhaidu** [j-easy/easy-rules#227]
When using YML file to write code, it is difficult to check the exceptional errors. Sometimes I don't know which line is wrong and the cause of the exceptions. Most exceptions come from compile-time exceptions. What's a good solution?

**Comment by yelf06** [comment]
You could maybe create an interface with a method that you would call in the yml file. This way, you could handle the exceptions in the interface implementation

**Comment by benas** [comment]
Easy Rules can really do nothing to help here. That's the issue of writing code in Yaml.
