### ISSUE TITLE
Java 8 upgrade(Using streams etc.)

### ISSUE THREAD

**Issue by chwoerz** [j-easy/easy-rules#231]
Hey @benas I've seen your project and saw, that it still was on Java 7. I've created a fork of easy-rules and upgraded the code to Java 8. Could you spare some time and look over it, if you like my [changes](https://github.com/chwoerz/easy-rules)? I've tried to simplify some code. I would be especially thankful if you could check the `RuleDefinitionValidator` class, where I've simplified the check for parameter types.

The tests are all passing and if it looks okay to you, I will create a pull request.

Thanks

**Comment by benas** [comment]
I was about to upgrade to Java 8 for v3 but some users wanted to keep Java 7 ( See #81 ). Moving to Java 8 is planned for v4. You are welcome to open a PR for the next major version!
