### ISSUE TITLE
Query: How to implement AND between 2 rules.

### ISSUE THREAD

**Issue by biswabandhu21** [j-easy/easy-rules#232]
I have a use case where if one of the rule satisfies then how can I stop the evaluation of other rule.

Eg

Rule 1 
Rule 2
Rule 3
Rule 4
I want to able to implement And operator between rules, currently it runs all the rules for given fact.

Please suggest if this is possible or I will have to implement it outside of the rule engine.

**Comment by biswabandhu21** [comment]
I mean something like Rule 1 & Rule 2 OR Rule 3 or Rule 4

@benas : Can you please help

**Comment by benas** [comment]
> I have a use case where if one of the rule satisfies then how can I stop the evaluation of other rule.

`skipOnFirstAppliedRule` is what you are looking for, see here: https://github.com/j-easy/easy-rules/wiki/defining-rules-engine#rules-engine-parameters

> I want to able to implement And operator between rules,

For that, you can use one of the [composite rules](https://github.com/j-easy/easy-rules/wiki/defining-rules#composite-rules) provided by Easy Rules or create a custom one if needed.

**Comment by keith-java** [comment]
> I mean something like Rule 1 & Rule 2 OR Rule 3 or Rule 4
> 
> @benas : Can you please help

help! how to implement OR between 2 rules.
