### ISSUE TITLE
Make AbstractRuleEngine public

### ISSUE THREAD

**Issue by MatiWalk** [j-easy/easy-rules#238]
Hey, first of all, great library! We are thinking on using this on our project.

Could we make `AbstractRuleEngine` public? right now it's only package accessible and it'd be cool to add new custom implementations to that base code. Perhaps making the other implementations not final could also work.

Thanks in advance!

**Comment by MatiWalk** [comment]
Adding to the above, I'm seeing DefaultRuleListener is also not public, so there's no way of using it on a custom engine

**Comment by benas** [comment]
Hi @MatiWalk ,

> Hey, first of all, great library! We are thinking on using this on our project.

Thank you! I'm glad you like Easy Rules!

I made `AbstractRulesEngine` public, it makes sense to me.

In regards to `DefaultRuleListener`, it has been removed in #223 .

**Comment by MatiWalk** [comment]
Thank you so much!

any expected release date for 3.4?

**Comment by benas** [comment]
I did not set a release date, but it should be out soon (probably by the end of November). Keep tuned 😉
