### ISSUE TITLE
org.jeasy.rules.api.Rules issue

### ISSUE THREAD

**Issue by yunfengwang** [j-easy/easy-rules#243]
Hi, I find two issues in the class Rules  one is construct  and the other is unregister method:

```java
public Rules(Object... rules ) {
        for (Object rule : rules) {
            this.register(RuleProxy.asRule(rule));
        }
}
```

it should be:
```java
public Rules(Object... rules ) {
        for (Object rule : rules) {
            this.register(rule);
        }
  }
```

and 

```java
public void unregister(Object rule) {
        Objects.requireNonNull(rule);
        rules.remove(RuleProxy.asRule(rule));
    }
```
it should be:

```java
public void unregister(Object rule) {
        Objects.requireNonNull(rule);
        rules.remove(rule);
    }
```

look forward to your reply!

**Comment by benas** [comment]
The first one is correct, good catch! I fixed it in 6e4ac46.

The second one however is not correct, because it will fail [this test](https://github.com/j-easy/easy-rules/blob/master/easy-rules-core/src/test/java/org/jeasy/rules/api/RulesTest.java#L60-L67).
