### ISSUE TITLE
Vulnerabilities in Jackson Databind 2.9.9

### ISSUE THREAD

**Issue by DrJErving** [j-easy/easy-rules#244]
First off, happy new year!!! And thanks for creating this great library, we are using it as part of a project and it rocks!
However, we ran a security scan and found out that there are some vulnerabilities on jackson-databind@2.9.9

You can take a look here to the list:
https://www.cvedetails.com/vulnerability-list/vendor_id-15866/product_id-42991/Fasterxml-Jackson-databind.html

All issues seems to be fixed at version 2.10.1
https://snyk.io/vuln/maven:com.fasterxml.jackson.core:jackson-databind@2.10.1

Would you mind updating the dependency version?

**Comment by benas** [comment]
Happy new year! Glad to hear you are using Easy Rules!

Thank you for opening this issue. This update was planned (as well as other dependency updates) for the upcoming v4. In the meantime, you can exclude the jackson version coming with easy rules and override it with 2.10.1.

I'm closing this issue as it was done in 666666c8f6479d85be9096c6eadd3613651df83e.

**Comment by DrJErving** [comment]
Thanks for the quick response! What is the planned date for the v4 release?
