### ISSUE TITLE
Getting evaluation result (audit)

### ISSUE THREAD

**Issue by agseco** [j-easy/easy-rules#246]
Hi,

I'm considering using `easy-rules`in a project and one important requirement is to be able to get some sort of *reasoning stack* from every evaluated rule - this is called *audit* in [rulebook](https://github.com/deliveredtechnologies/rulebook).

For example, for illustration purposes let's say I have a composite rule `FlightRule` with these sub-rules:

- `SameDateRule` - generic rule to evaluate  whether a date equals to another date and takes these facts as input:
  - `inputDate` - in the context of evaluating a flight, it would be the flight's date
  - `expectedDate` - the date to compare with (reference)
- `RouteRule` - evaluates whether a flight operates a given route and takes these facts as input:
  - `inputRoute` - the flight route
  - `expectedRoute` - the route to compare with (reference)

If I executed `FlightRule`, I'd like to have the information of which conditions where met and which didn't for debugging/auditing purposes. After reading `easy-rules` wiki and some issues, I can think of the following strategies:

- Logging - not ideal, there will be too many log entries because there will be thousands of rules being evaluated in a matter of hours
- Implementing a custom `RuleListener` - seems cleaner but I will be lacking context in the scenario of complex composite rules (which I will have)
- Implementing a custom wrapper of `Rule` that has the capability of returning a result (similar as explained [here](https://github.com/j-easy/easy-rules/wiki/faqs#2-i-would-like-to-return-a-value-upon-a-rule-execution-how-to-do-that)) that is capable of generating composite results from sub-rules; I guess this may require wrapping or extending the `RulesEngine`too...

If I have elaborated properly my use case/requirement, I'd love to hear some advice in this regard.

Many thanks in advance :)

**Comment by agseco** [comment]
Hi again,

I just found issue #125 where the method [`RulesEngine.check(Rules rules, Facts facts)`](https://www.javadoc.io/static/org.jeasy/easy-rules-core/3.4.0/org/jeasy/rules/api/RulesEngine.html#check-org.jeasy.rules.api.Rules-org.jeasy.rules.api.Facts-) is pointed out.

This could be another option for me, however I'm guessing I'll have to 1) fire the rule and then 2) check to get the debug info In need. Ideally should do both actions at once.

Cheers.

**Comment by benas** [comment]
> I'm guessing I'll have to 1) fire the rule and then 2) check to get the debug info In need

`check` does not fire rules, it just checks if the condition of each rule is met against the set of given facts. You can think of it as a "dry run" with no side effects.

Does this answer your question?

**Comment by benas** [comment]
Closing this issue as I believe I answered the question. If not, don't hesitate to add a comment here.
