### ISSUE TITLE
Mention in the wiki that a module is required in order to use composite rules

### ISSUE THREAD

**Issue by agseco** [j-easy/easy-rules#247]
It's not hard to find your way around after few minutes, but IMHO it would help if the [composites rules wiki section](https://github.com/j-easy/easy-rules/wiki/defining-rules#composite-rules) mentioned that you need to explicitly add the dependency to `easy-rules-support`.

Apologies in advance if I have missed some point.

**Comment by benas** [comment]
Hi @agseco ,

Thank you for raising this! I updated the section as follows:

```
Easy Rules comes with 3 implementations of CompositeRule that can be found in the easy-rules-support module...
```

I hope this makes it clear enough.
