### ISSUE TITLE
Can we update/add new index inside a array using SPEL expression ?

### ISSUE THREAD

**Issue by ankitravan** [j-easy/easy-rules#248]
I have an json object like.

{
	"status": "success",
	"payload": {
		"list": [{
				"employeeId": "null"	
			}]	
	},
	"description": null,
	"metadata": null
}

And I am trying to update employeeId with SPEL Expression "['payload']['list'][0]['employeeId']".
Its working fine.

Now I have one more Expression like "['payload']['list'][1]['employeeId']". But original list property has only one object on 0th index.

So I want to add new object on index 1 using this "['payload']['list'][1]['employeeId']" expression.
Is it possible through this ?

Please suggest same or alternative.

**Comment by zhhaojie** [comment]
no doubt about it , yes.
use JSON API to parse  json string and then do whatever you want

**Comment by benas** [comment]
It should be possible. Please refer to the reference docs of SpEL to see how to do that.

I'm closing this issue because it is not specific to easy rules.

@zhhaojie Thank you for the follow up!
