### ISSUE TITLE
Can you add QLExpress Support?

### ISSUE THREAD

**Issue by chenlingmin** [j-easy/easy-rules#249]
Hi, [QLExpress](https://github.com/alibaba/QLExpress) is an open source expression language from Alibaba. Can you consider extending support?

**Comment by benas** [comment]
Hi, sure that would be great!

I suggest you create and maintain this module and I will be more than happy to add a reference to it here: https://github.com/j-easy/easy-rules#easy-rules-in-other-languages

Wdyt?

**Comment by benas** [comment]
I have no plan/time to work on a new module for QLExpress for now. If someone is interested, he/she can create the module on a repo they own/maintain (no need for a PR) and I would be happy to add a reference to it in the home page.
