### ISSUE TITLE
How to do chain reasoning

### ISSUE THREAD

**Issue by BeanSprouts** [j-easy/easy-rules#254]
Hi,I cannot find any examples for chain reasoning.
can easy rules do chain reasonings?

**Comment by benas** [comment]
What do you mean by "chain reasoning"? Can you give an example?

**Comment by BeanSprouts** [comment]
> What do you mean by "chain reasoning"? Can you give an example?

At the beginning, the facts only satisfied one rule，then the rule has be executed, and changed the facts to satisfy other rules, finally, the newer to be satisfied rules will be executed.

**Comment by benas** [comment]
`InferenceRulesEngine` is what you are looking for. You can find more details in the [wiki](https://github.com/j-easy/easy-rules/wiki/defining-rules-engine) and an example in [this tutorial](https://github.com/j-easy/easy-rules/wiki/air-conditioning).
