### ISSUE TITLE
Ability to define rules without specifying actions

### ISSUE THREAD

**Issue by 0xjjoyy** [j-easy/easy-rules#255]
Hello,

I'd like to not have to specify 'actions' in my rules (YAML) file? How can I do this?

The actions should be handled in my application logic based on the results of running against my rule files, not embedded in my rules.

If I try to leave out actions, I receive the following error.

```
Exception in thread "main" java.lang.IllegalArgumentException: The rule action(s) must be specified
at org.jeasy.rules.support.AbstractRuleDefinitionReader.createRuleDefinition(AbstractRuleDefinitionReader.java:86)
at org.jeasy.rules.support.AbstractRuleDefinitionReader.createRuleDefinition(AbstractRuleDefinitionReader.java:99)
at org.jeasy.rules.support.AbstractRuleDefinitionReader.read(AbstractRuleDefinitionReader.java:44)
at org.jeasy.rules.mvel.MVELRuleFactory.createRules(MVELRuleFactory.java:101)
at org.jeasy.rules.mvel.MVELRuleFactory.createRules(MVELRuleFactory.java:90)
```

**Comment by benas** [comment]
It does not make sense to have a rule with only a condition but no action(s). This would mean I want to test something and then do nothing.. A rule must define one condition and at least one action. Please refer to [this section](https://github.com/j-easy/easy-rules/wiki/defining-rules) of the wiki.

Easy Rules was designed as an implementation of a [production system](https://en.wikipedia.org/wiki/Production_system_(computer_science)) where [Productions](https://en.wikipedia.org/wiki/Production_system_%28computer_science%29) consist of two parts: a sensory precondition (or "IF" statement) and an action (or "THEN"). You can find more details in the [FAQs](https://github.com/j-easy/easy-rules/wiki/faqs#7-why-there-is-no-else-support-in-easy-rules).

**Comment by 0xjjoyy** [comment]
I'm sorry, though you are misinterpreting what I wrote. I'm asking to decouple fine grained rules against a larger ruleset to actions.

**Comment by benas** [comment]
That's what I understood from the title of the issue "Ability to define rules without specifying actions". But in that case, I'm sorry for mis-understanding your concern.

Now in order to avoid any further mis-interpretation, please provide an example of what you are trying to achieve to see if Easy Rules is a good fit for your use case.

**Comment by 0xjjoyy** [comment]
An example use case is as follows.

Definition of multiple composite rules. If any of the composite rules matches, Then trigger a defined Action.

The multiple composite rules can be defined in a single YAML file or multiple YAML files.

The Action to trigger can be defined by a parameter specified in Java Code at the loading of the particular YAML file(s).

It will not be required to specify an Action or Java code in the YAML file.

Thanks

**Comment by benas** [comment]
Thanks for the updates.

> Definition of multiple composite rules. If any of the composite rules matches, Then trigger a defined Action.

This is a good candidate for a custom composite rule with its own [Action](https://github.com/j-easy/easy-rules/blob/master/easy-rules-core/src/main/java/org/jeasy/rules/api/Action.java) (which can be specified at construction time of the custom composite rule).

There is no plan for now to introduce the possibility to define a rule without actions. This can be done in a fork.
