### ISSUE TITLE
How to call function inside MVELAction

### ISSUE THREAD

**Issue by NessrineHallal** [j-easy/easy-rules#256]
Hello ,
i'm looking for best practices to call predefined function inside actions. I will be thankful if you can help. 
 
when i tried to call a function in action , i got this error :
[error] o.j.r.c.DefaultRulesEngine - Rule 'door open alert' performed with error
org.mvel2.PropertyAccessException: [Error: null pointer or function not found: test]

**Comment by benas** [comment]
Hi,

You can try to:

* Define your function inline in the MVEL expression then invoke it in the action (See example [here](https://github.com/j-easy/easy-rules/blob/1a56c9f67aca18238c53330eb86bd1f72b38ed06/easy-rules-mvel/src/test/java/org/jeasy/rules/mvel/MVELActionTest.java#L60), inspired by [MVEL's docs](http://mvel.documentnode.com/#function-definition))
* Import your function definition through a `ParserContext` and invoke in your action (See example [here](https://github.com/j-easy/easy-rules/blob/1a56c9f67aca18238c53330eb86bd1f72b38ed06/easy-rules-mvel/src/test/java/org/jeasy/rules/mvel/MVELActionTest.java#L90))

Does this help?

Kr,
Mahmoud

**Comment by NessrineHallal** [comment]
In our case the rule in defined in Json file , something like this : [
{
name: "door open alert",
description: "",
priority: 1,
condition: "value.equals("Open")",
actions: [
"Alert(value);"
]
}
],

**Comment by benas** [comment]
ok and where is the `Alert` function defined? You should be able to import it using a `ParserContext` and use it in your rule's action. Here is a quick example: given the following `alert-rule.json` file:

```json
[
  {
    "name": "alert rule",
    "condition": "true",
    "actions": [
      "alert(value)"
    ]
  }
]
```

If you run this example:

```java
import java.io.File;
import java.io.FileReader;

import org.jeasy.rules.api.Facts;
import org.jeasy.rules.api.Rules;
import org.jeasy.rules.api.RulesEngine;
import org.jeasy.rules.core.DefaultRulesEngine;
import org.jeasy.rules.support.JsonRuleDefinitionReader;
import org.mvel2.ParserContext;

public class GH256Example {
	
	public static void main(String[] args) throws Exception {
		MVELRuleFactory factory = new MVELRuleFactory(new JsonRuleDefinitionReader());
		File rulesDescriptor = new File("alert-rule.json");
		ParserContext parserContext = new ParserContext();
		parserContext.addImport("alert", GH256Example.class.getMethod("alert", String.class));
		Rules rules = factory.createRules(new FileReader(rulesDescriptor), parserContext);
		Facts facts = new Facts();
		facts.put("value", "hello world");

		RulesEngine rulesEngine = new DefaultRulesEngine();
		rulesEngine.fire(rules, facts);
	}
	
	public static void alert(String value) {
		System.out.println(value);
	}
}
```

it prints: `hello world`, which means the function has been successfully registered and invoked the rule.

Does this help?

**Comment by benas** [comment]
Is the method `addNotification` in class `ProcessingActor` static? I think MVEL can only work with static methods as it won't instantiate your class and invoke the method on the instance.

**Comment by NessrineHallal** [comment]
Yes , that was the problem , now it works perfectly .Thank you so much !

**Comment by benas** [comment]
Great. You are welcome, glad it helped!
