### ISSUE TITLE
Add BeanResolver to SpELAction and SpELCondition

### ISSUE THREAD

**Issue by elitacco** [j-easy/easy-rules#259]
Hi

I would like to be able to reference spring managed beans from SpEL actions/conditions. Something like this: 
`@myBean.myMethod(#myFact, 1234)`

I know I could add the bean to the facts and then use it like this.
`#myBean.myMethod(#myFact, 1234)`

But that means that I have to add all the beans I need to the facts every time I create a rule. If we are talking about dozens of beans this is clearly not the best way to do it. It would be better to allow to pass the BeanResolver in the constructor then set it in the context created in the [evaluate](https://github.com/j-easy/easy-rules/blob/9fc5a8f2e284c39e74d9a499cdd7a1e09f89dd57/easy-rules-spel/src/main/java/org/jeasy/rules/spel/SpELCondition.java#L78) and [execute](https://github.com/j-easy/easy-rules/blob/9fc5a8f2e284c39e74d9a499cdd7a1e09f89dd57/easy-rules-spel/src/main/java/org/jeasy/rules/spel/SpELAction.java#L78) methods.

Thanks

**Comment by benas** [comment]
Hi @elitacco ,

Thank you for opening this issue. This makes sense. I added the ability to provide a bean resolver to SpEL conditions and actions at construction time (See fcfb2ad). This is useful when using the `RuleBuilder` and creating the condition/actions manually.

If you use the `SpELRuleFactory` to create rules, then you can pass the bean resolver to the factory at construction time as well.

I deployed these changes in [v4.0.0-SNAPSHOT](https://github.com/j-easy/easy-rules/wiki/getting-started#use-a-snapshot-version). Can you give it a try and share your feedback?

Thank you upfront!

**Comment by elitacco** [comment]
That's exactly what I had envisioned!
I ran some test and it works as expected.
Any ETA for v.4.0.0?

Thanks again

**Comment by benas** [comment]
Perfect! Thank you for taking the time to test and give your feedback.

> Any ETA for v.4.0.0?

Not really, with all these hard times.. But my main focus is on easy rules now, so keep tuned on project updates.
