### ISSUE TITLE
Cannot use in EhCache

### ISSUE THREAD

**Issue by yuefei7746** [j-easy/easy-rules#260]
In my application, my yaml text is saved in the database, so I need to read it from the database and load it as a rules object every time I execute it, so I want to put it into EhCache, but the rules object does not realize serializable, now I have compiled a custom MyRules To replace it, but I still hope that this feature can be supported in your library.

**Comment by benas** [comment]
This is similar to #159 but for ehcache instead of spark.

> now I have compiled a custom MyRules To replace it

Can you share what you did? If it is reasonable enough without introducing too much complexity, I can consider adding it.

**Comment by benas** [comment]
As mentioned in https://github.com/j-easy/easy-rules/issues/159#issuecomment-482925343, there is no plan to make almost all APIs implement serializable.

I'm closing this issue, thank you for raising it anyway.
