### ISSUE TITLE
action里只能使用void方法，请问，执行fire()方法后，想要返回Object对象，怎么处理？

### ISSUE THREAD

**Issue by xukk1992** [j-easy/easy-rules#270]

**Comment by benas** [comment]
Thank you for opening this issue. Could you please write the title in English? I tried to use a translation service but I could not understand the question.

Thank you upfront.

**Comment by zhhaojie** [comment]
@xukk1992 
there is NO return Value on execute method !
If you want to get the result (may be `Object对象` ), there are at least two way to achieve that.
-  Use `RuleListener`  Or `RulesEngineListener`
-  Set result to the facts .  then example is [ https://github.com/j-easy/easy-rules/wiki/faqs#2](url)

by the way in my opinion ,  do NOT block the ruleEngine when you use the execute result.

**Comment by benas** [comment]
ok I think I understand now after seeing the comment by @zhhaojie . This is a frequently asked question and the answer is in the wiki as mentioned by @zhhaojie : https://github.com/j-easy/easy-rules/wiki/faqs#2-i-would-like-to-return-a-value-upon-a-rule-execution-how-to-do-that.

@zhhaojie Thank you very much for the follow up!
