### ISSUE TITLE
How can I define my Composite rules in JSON file？

### ISSUE THREAD

**Issue by Venus-WXP** [j-easy/easy-rules#272]
I am a easy-rules beginner, I am very interesting for this project, thanks! Now I encounter a requirement how to define composite rules in json file. I cant find any resolutions. What should I do for this?Thanks

**Comment by benas** [comment]
Thank you!

You can find an example of how to define composite rules in a Json file here: https://github.com/j-easy/easy-rules/blob/master/easy-rules-support/src/test/resources/composite-rules.json
