### ISSUE TITLE
Can i get the name of the rule which hit/match the facts?

### ISSUE THREAD

**Issue by codeinmyself** [j-easy/easy-rules#274]
```java
engine.fire(rules, facts); 
```
How can i get the name of the rule which hits/matches the facts?

**Comment by benas** [comment]
Prior to firing rules, you can do a "dry run" with `RulesEngine#check`. This method returns a `Map<Rule, Boolean>` that allows you to know which rule matches the facts.

**Comment by codeinmyself** [comment]
Thanks for your reply.
But there has another question,the map return all rules which match the facts,
In my opinion, it should returns the first rule that match the facts.
