### ISSUE TITLE
I can't get the condition from MVELCondition

### ISSUE THREAD

**Issue by codeinmyself** [j-easy/easy-rules#277]
```java
public class MVELRule extends BasicRule {

    private Condition condition = Condition.FALSE;
}
```
the Class 'MVELRule' doesn't have 'get' function for condition, so i can't get condition from it

**Comment by benas** [comment]
When you create a `MVELRule` instance, you know the condition that you set on the rule. Why do you need to get it afterwards?

**Comment by benas** [comment]
I'm closing this as I believe there is no need for a getter for the condition/action.
