### ISSUE TITLE
[BUG] Sometimes, rule.execute(facts); would not be executed or couldn't get @Action annotated method if fire rules during service startup

### ISSUE THREAD

**Issue by shanhq96** [j-easy/easy-rules#279]
Version: easy-rules 3.4
I defined rules by annotation.

If large request to service during startup, i.e. fire rules during startup.
Sometimes the rule.execute(facts) in DefaultRulesEngine would not be executed (or executed but can't find the `@Action` annotated method). I added some log in the `@Action` annotated method but it not occurred.

When error:
org.jeasy.rules.core.DefaultRulesEngine: Rule 'DummyRuleName' triggered
org.jeasy.rules.core.DefaultRulesEngine: Rule 'DummyRuleName' performed successfully

When normal:
org.jeasy.rules.core.DefaultRulesEngine: Rule 'DummyRuleName' triggered
DummyRule: action method executed
org.jeasy.rules.core.DefaultRulesEngine: Rule 'DummyRuleName' performed successfully

This would not be reproduced every time, it only occurred sometimes. And only occurred during deployment.

Would you please help to figure out the root cause?

**Comment by benas** [comment]
> I added some log in the `@Action` annotated method but it not occurred.

How do you log `DummyRule: action method executed`? Using `System.out.println` or using a proper logger? Sometimes the buffer of `System.out` could be flushed before/after the logger used by Easy Rules. Are you sure `DummyRule: action method executed` is not logged at all? It could be there but a couple of lines before or after the log of Easy Rules.

I don't see how this could be related to Easy Rules, so I'm closing this issue. Feel free to add a comment if you need further support.

**Comment by shanhq96** [comment]
Actually, it doesn't matter the approach to log, in our prod, I put a value to Facts. But I can't get the value after firing rules.
During my debug, I add some log to the @Action method to figure out what happened. Then I found the log can't be printed sometimes. It means the @Action method was not executed.
