### ISSUE TITLE
Has the rule changed or is it a bug?

### ISSUE THREAD

**Issue by lu-cheng** [j-easy/easy-rules#280]
In 3.4.0 version, it ‘s working.   But in version 4.0.0, it does not work.

```json
[
	{
		"name": "rule1",
		"description": "Test json rule",
		"priority": 0,
		"condition": "true",
		"actions": [
			"x = 100"
		]
	},
	{
		"name": "rule2",
		"description": "Test json rule",
		"priority": 1,
		"condition": "x == 100",
		"actions": [
			"System.out.println(x);"
		]
	}
]
```

**Comment by zhhaojie** [comment]
Hi, I did some tests on easy-rules(3.4.0) with MVEL(2.4.3) and easy-rules(4.0.0) with MVEL(2.7.0)
the answer is yes. the rules you have given above did not get the same result.  Not because MVEL
but easy-rules(4.0.0) bring a change of facts `Facts#asMap`.
More details here: [https://github.com/j-easy/easy-rules/issues/267#issue-588049406](url)

**Comment by lu-cheng** [comment]
Can't figure out why it should be changed. This syntactic sugar is very good. In fact, the rules engine should be decoupled from the actual business, rules and data are variable. Therefore, the operation result will actually be returned in Json format. This does not fundamentally change the fact that weak types are available, I can still add Map to the Facts. Don't turn EasyRules into Drools.

**Comment by benas** [comment]
Thank you for reporting this issue. Why did you close it?

Can you please share how are you running the rules? Are you adding `x` as fact before firing rules?

**Comment by lu-cheng** [comment]
Sorry，I reopen it.
In my opinion, this change is of little help to the type, it just makes us lose the syntactic sugar.
For example：
3.4.0 version
```java
    @SneakyThrows
    @PostMapping(path = { "/json" })
    public ResponseEntity<?> test(@RequestBody String body) {
        Reader reader = new StringReader(body);
        MVELRuleFactory ruleFactory = new MVELRuleFactory(new JsonRuleDefinitionReader());
        Rules rules = ruleFactory.createRules(reader);
        RulesEngine rulesEngine = new DefaultRulesEngine();
        Facts facts = new Facts();
        Map<String, ?> result = new HashMap<>();
        facts.put("result", result);
        rulesEngine.fire(rules, facts);
        return ResponseEntity.ok(result);
    }
```
```json
[
	{
		"name": "rule1",
		"description": "Test json rule",
		"priority": 0,
		"condition": "true",
		"actions": [
			"x = 100"
		]
	},
	{
		"name": "rule2",
		"description": "Test json rule",
		"priority": 1,
		"condition": "x == 100",
		"actions": [
			"result.x = x"
		]
	}
]
```

4.0.0 version
```java
facts.put("$", new HashMap<>());
```
```json
[
	{
		"name": "rule1",
		"description": "Test json rule",
		"priority": 0,
		"condition": "true",
		"actions": [
			"$.x = 100"
		]
	},
	{
		"name": "rule2",
		"description": "Test json rule",
		"priority": 1,
		"condition": "$.x == 100",
		"actions": [
			"result.x = $.x"
		]
	}
]
```

**Comment by lu-cheng** [comment]
Because when writing rules, intermediate variables are often used, otherwise it will be repeatedly calculated and difficult to read. The changes in version 4.0.0 make writing and reading more complicated.

**Comment by zhhaojie** [comment]
> Because when writing rules, intermediate variables are often used, otherwise it will be repeatedly calculated and difficult to read. The changes in version 4.0.0 make writing and reading more complicated.

rule 1 you set x=100, 
and rule 2 the x (changed by rule 1)eq 2, then you expect get the result after fire?
It’s that you want?

**Comment by lu-cheng** [comment]
Temporary intermediate variables cannot be predicted, so this is not what I need.
These examples are only used to reflect usage differences between versions. This is very important. This difference may lead to the need to modify rules when migrating versions.
See m in the example below
**rule0 is used for analog input parameters**
```json
[
    {
        "name": "rule0",
        "description": "Test json rule",
        "priority": 0,
        "condition": "true",
        "actions": [
            "t1 = 613",
            "t2 = 609",
            "dataTimestamp = System.currentTimeMillis()",
            "status = 1",
            "statusTimestamp = System.currentTimeMillis() - 1000*60*1",
            "fine = 0"
        ]
    },
    {
        "name": "rule1",
        "description": "Test json rule",
        "priority": 1,
        "condition": "(610 < t1 && t1 <= 613 && status == 0) || (608 < t2 && t2 <= 610 && status == 0)",
        "actions": [
            "status = 1",
            "statusTimestamp = dataTimestamp"
        ]
    },
    {
        "name": "rule2",
        "description": "Test json rule",
        "priority": 2,
        "condition": "t1 <= 610 && t2 <= 608",
        "actions": [
            "status = 0"
        ]
    },
    {
        "name": "rule3",
        "description": "Test json rule",
        "priority": 3,
        "condition": "t1 > 613 || t2 > 610",
        "actions": [
            "status = 2",
            "statusTimestamp = dataTimestamp"
        ]
    },
    {
        "name": "rule4",
        "description": "Test json rule",
        "priority": 4,
        "condition": "status == 1",
        "actions": [
            "m = Math.floor((dataTimestamp - statusTimestamp)/1000/60)"
        ]
    },
    {
        "name": "rule5",
        "description": "Test json rule",
        "priority": 5,
        "condition": "m < 2",
        "actions": [
            "fine += 10"
        ]
    },
    {
        "name": "rule6",
        "description": "Test json rule",
        "priority": 6,
        "condition": "m >= 2 && m < 5",
        "actions": [
            "fine += 10 + (m - 2) * 10"
        ]
    },
    {
        "name": "rule7",
        "description": "Test json rule",
        "priority": 7,
        "condition": "m >= 5",
        "actions": [
            "fine += 50 + (m - 5) * 20"
        ]
    },{
        "name": "rule8",
        "description": "Test json rule",
        "priority": 8,
        "condition": "true",
        "actions": [
            "result.status = status",
            "result.statusTimestamp = statusTimestamp",
            "result.fine = fine"
        ]
    }
]
```

**Comment by benas** [comment]
@lu-cheng Thank you for adding these details. According to your comments and examples, I understand that when you write a rule like "rule1":

```json
{
  "name": "rule1",
  "description": "Test json rule",
  "priority": 0,
  "condition": "true",
  "actions": [
    "x = 100"
  ]
}
```

you are you expecting Easy Rules to add a fact named "x" with value "100". But what is the type of "x"? Since the type is undefined, this can lead to all kind of type safety issues. Here are some examples:

### Example 1: Trying to access a fact after firing rules:

```java
public class Launcher {
	public static void main(String[] args) {
		MVELRule rule1 = new MVELRule().name("rule1").description("Test json rule")
				.priority(0)
				.when("true")
				.then("x = 100"); // weakly typed
		Rules rules = new Rules();
		rules.register(rule1);
		Facts facts = new Facts();
		RulesEngine rulesEngine = new DefaultRulesEngine();
		rulesEngine.fire(rules, facts);
		short x = facts.get("x"); // I don't know the type of x, so let's try "short" ...
		System.out.println("x = " + x);
	}
}
```

This fails with `java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Short`.

### Example 2: 

```json
[
  {
    "name": "rule1", "description": "Test json rule", "priority": 0,
    "condition": "true",
    "actions": [
      "x = 10000000000000000000"
    ]
  },
  {
    "name": "rule2", "description": "Test json rule", "priority": 1,
    "condition": "x + 1 > 0",
    "actions": [
      "System.out.println(x);"
    ]
  }
]
```

This fails with `java.lang.NumberFormatException: For input string: "10000000000000000000"`

One of the motivations of adding the `Fact` API is type safety (#276), which hopefully will make it easier to avoid such kind of issues. So I would argue that if there is a problem, then this problem is with v3.4 and not with v4.0.

> it just makes us lose the syntactic sugar

You probably lose a syntactic sugar, but you definitely gain type safety.

> rule0 is used for analog input parameters

This is an anti-pattern. You don't need such rule with a condition always equal to `true` just to assign variables. Add those variables as **typed** facts before firing rules.

Moreover, the approach you are suggesting is still not type safe:

```java
// with v3.4
Map<String, ?> result = new HashMap<>();
facts.put("result", result);

// with v4.0
facts.put("$", new HashMap<>());
```

In both cases, the type of fact values is undefined since you use `Object`. The way to proceed with your last example is:

1. Remove `rule0`, you don't need this
2 Create a holder class with **typed** fields and add those as typed facts:

```java
class Holder {
   long dataTimestamp;
   long statusTimestamp;
   // other variables with correct types
}

Facts facts = new Facts();
Holder holder = new Holder();
// initialize holder if needed
facts.put("h", holder); // Then use `h.` prefix in your EL expressions.
rulesEngine.fire(rules, facts);
```

Do you agree?

**Comment by benas** [comment]
I'm closing this based on the reasons explained in details in my previous comment.
