### ISSUE TITLE
Junit test over ConditionalRuleGroup

### ISSUE THREAD

**Issue by JuanPalacios** [j-easy/easy-rules#281]
Hello,

How could I unit test my conditional rule group, I'm not sure.
I tried with an engine listener but only the conditional rule is listened, so, I can't ensure that the right rule was thrown. I need to ensure that the end rule is applied.

Thanks in advance

**Comment by benas** [comment]
You can mock/stub the conditional rule and check if composing rules have been executed or not. You can find examples here: https://github.com/j-easy/easy-rules/blob/master/easy-rules-support/src/test/java/org/jeasy/rules/support/composite/ConditionalRuleGroupTest.java

**Comment by JuanPalacios** [comment]
Thanks, let me check
