### ISSUE TITLE
Several rules and one ramdom is not evaluated

### ISSUE THREAD

**Issue by JuanPalacios** [j-easy/easy-rules#282]
I was testing with four simple rules and the DefaultRulesEngine and one of the rule is not evaluated, it seems to be totally ramdom the one skipped.

**Comment by benas** [comment]
I don't see how this could be random (unless you have random facts), so please provide an example that reproduces the problem.

I'm closing this issue for now, but we can re-open it if we confirm there is a bug.

**Comment by JuanPalacios** [comment]
The proble was the name of the rule, I was putting two rules with the same name.

Thanks
