### ISSUE TITLE
Add size method in Rules API

### ISSUE THREAD

**Issue by Desislav-Petrov** [j-easy/easy-rules#283]
Hi,

As a part of the Rules class interface it will be useufl to have a size/count method which will return how many rules are loaded, I'm happy to do a PR if people agree with the feature.

Thanks,
Des

**Comment by zhhaojie** [comment]
agree!

**Comment by benas** [comment]
This makes sense to me. In fact, I see no straightforward way to get the rules count with the current API as of v4.0. To get the rules count, one needs to iterate over `Rules#iterator` and count the rules or do something like `StreamSupport.stream(rules.spliterator(), false).count();` which are both not convenient.

I merged #284 for this.

@Desislav-Petrov Thank you for raising this issue and for contributing the PR!
