### ISSUE TITLE
Use of If-Else conditions in easy rules.

### ISSUE THREAD

**Issue by Yogesn** [j-easy/easy-rules#286]
Can we create if-else condition-based rules? Currently, easy-rules supports only one condition to be evaluated with Logical operators. Is there any other way using MVEL / SpEL, we can create complex conditions?

Thank you upfront.

**Comment by benas** [comment]
> Can we create if-else condition-based rules?

No, please check the [FAQs](https://github.com/j-easy/easy-rules/wiki/faqs#7-why-there-is-no-else-support-in-easy-rules).
