### ISSUE TITLE
Rules class cannot accept Comparable

### ISSUE THREAD

**Issue by avakimov** [j-easy/easy-rules#291]
Hello
I've noticed that `RuleProxy` implementation calls `compareTo` if target has that method implemented. But it wouldn't work
I've added unit test to my easy-rules fork, to demonstrate this behaviour. 
https://github.com/j-easy/easy-rules/commit/17f8bbb9dae349d476ad81078fcb3771599cf771

**Comment by benas** [comment]
@avakimov Thank you for opening this issue! Indeed, there is an argument type mismatch when trying to register a proxy for a type implementing `Comparable`.

It should be fixed now in 4.1.0-SNAPSHOT. It would be appreciated if you give it a try and share your feedback.
