### ISSUE TITLE
基于yml文件异常

### ISSUE THREAD

**Issue by caoguofeng92** [j-easy/easy-rules#296]
我把规则配置在yml文件中，结果在执行时只匹配到第一个规则，

**Comment by benas** [comment]
@caoguofeng92 Can you please write your message in English? Here is what I get from google translate (but I will let you confirm):

> I configured the rule in the yml file, and the result only matches the first rule when it is executed

I can't help without seeing your rules and facts. So please share more details to be able to help you.
