### ISSUE TITLE
does it support rule-chain & rule-chain-result-output

### ISSUE THREAD

**Issue by endypark** [j-easy/easy-rules#300]
the input is just Facts, but no output.

does it support rule-chain-result-output, such as the error-message-array ?

**Comment by benas** [comment]
No, rules do not return values, please check the [FAQs](https://github.com/j-easy/easy-rules/wiki/faqs#2-i-would-like-to-return-a-value-upon-a-rule-execution-how-to-do-that) for more details about that matter.
