### ISSUE TITLE
Can we use this with SpringCloudDataFlow

### ISSUE THREAD

**Issue by koladilip** [j-easy/easy-rules#301]
Hi,

Thanks for great library, I am exploring this, can we use it along with Spring Cloud Data flow?
https://github.com/spring-cloud/spring-cloud-dataflow

- Dilip

**Comment by benas** [comment]
Hi, 

> Thanks for great library,

Thank you!

> can we use it along with Spring Cloud Data flow?

You should be able to use Easy Rules in SCDF depending on how you design and package your app (task or stream). I think the nature of your input facts is key:

* If facts are a fixed set of data items, then you can apply rules on the **fixed set of known facts** and deploy your Easy Rules app as a Spring Cloud Task. This is a **proactive** approach: we know facts upfront, so we can proactively act on them.
* If facts are a stream of events, then you can apply rules on **windows of facts** and deploy your Easy Rules app as a Spring Cloud Stream. This is a **reactive** approach: we don't know facts upfront, so we will react on them as they happen.

I'm closing this issue for now, but don't hesitate to add a comment if you need further support.
