### ISSUE TITLE
No sample code to find how to evaluate the rules before firing

### ISSUE THREAD

**Issue by rahamathulla-ai** [j-easy/easy-rules#306]
No sample code to find how to evaluate the rules before firing. Please add samples for this

**Comment by benas** [comment]
Evaluating rules boils down to calling `rulesEngine.check(rules, facts)`, which returns a `Map` of evaluation results.

I don't know what are you specifically looking for, but [this unit test](https://github.com/j-easy/easy-rules/blob/a999f461534d99928257bb114a303712ee737e9d/easy-rules-core/src/test/java/org/jeasy/rules/core/DefaultRulesEngineTest.java#L168-L183) shows an example.
