### ISSUE TITLE
What is the rule inference algorithm used in easy-rules?

### ISSUE THREAD

**Issue by samyc1201** [j-easy/easy-rules#309]
I can't find any document specifying this, is easy-rules using Rete algorithmn internally? Or?

I found this in the FAQ:

`Easy Rules also provides an inference rules engine. This engine is less stupid than the default one: Given a set of facts, it continuously selects and applies rules until no more rules are applicable. `

But how does `InferenceRulesEngine` work compare to the `DefaultRulesEngine`, in term of performance, would that be big different too?

**Comment by rahamathulla-ai** [comment]
as far as i understand, inference rule engine trigger the rules continuously until certain condition is met, where as defaultruleengine will fire the rules once. see the air cooler example in the documentation

**Comment by benas** [comment]
As @rahamathulla-ai mentioned, the difference is that the `DefaultRulesEngine` fires rules only once, while the `InferenceRulesEngine` continuously fires applicable rules until no more rules are applicable. In pseudo-code, it's something like:

```java
Set<Rule> candidateRules;
do {
   candidateRules = selectCandidates(rules, facts);
   file(candidateRules);
} while (! candidateRules.isEmpty());
```

Candidate rules are the ones with a condition that evaluates to true against the given facts. I updated the [FAQ](https://github.com/j-easy/easy-rules/wiki/faqs#1-why-is-easy-rules-called-the-the-stupid-java-rules-engine) to add this clarification. The FAQ also provides a link to an example, which is the [air conditioning tutorial](https://github.com/j-easy/easy-rules/wiki/air-conditioning).

In terms of performance, the difference depends on how many iterations the process requires until no more rules are applicable. In the best case scenario, where a single iteration is needed, the performance will be equal to `DefaultRulesEngine`.

@rahamathulla-ai Thank you for the follow up!
