### ISSUE TITLE
Checking the Rule State as True or False

### ISSUE THREAD

**Issue by bellini-ea** [j-easy/easy-rules#311]
Hello,
I have been playing around with easy-rules and like what I am seeing so far.  In a simplistic case, I'm looking to determine if the state of a rule is true or false.  The only way I can see how to do this so far is to use the listener or a method annotated with @Action.  This is sort of fine for me use case, but the issue because knowing when the Rule did not evaluate (i.e. its rule state False).  The way easy-rules handles this so far is the "lack of" the listener being called or the @Action method being called.

Seems like I need to implement something that keeps the state of all the rules after the execution so that it can be queried.  

This is working for me and maybe the expected way I presume:

```
Map<Rule, Boolean> ruleStates = rulesEngine.check(rules, facts);
for ( Map.Entry<Rule, Boolean> entry : ruleStates.entrySet() ) {
    System.out.println(String.format("Rule=%s State=%b", entry.getKey().getName(), entry.getValue()));
}
```

Appreciate any thoughts and/or insight on this.

**Comment by samyc1201** [comment]
Does this [rule listener](https://github.com/j-easy/easy-rules/wiki/defining-rules-listener) help? 

This method seems like it is what you need:

```
/**
     * Triggered after the evaluation of a rule.
     *
     * @param rule that has been evaluated
     * @param facts known after evaluating the rule
     * @param evaluationResult true if the rule evaluated to true, false otherwise
     */
    default void afterEvaluate(Rule rule, Facts facts, boolean evaluationResult) { }
```

You can obtain `evaluationResult` result after evaluate, in this case, you will know before `@action`, which is in the `@condition`. I never try this listener yet, but I guess it should work.

**Comment by benas** [comment]
Rules are better designed to be stateless, but you can use a flag to keep the evaluation result in the rule's state and query it later on if you want (See example in the [wiki](https://github.com/j-easy/easy-rules/wiki/faqs#2-i-would-like-to-return-a-value-upon-a-rule-execution-how-to-do-that)). This flag can be set in an action method or using a listener as mentioned by @samyc1201 . `RuleEngine#check` is indeed another option, if you don't want to keep the state in your rules.

@bellini-ea  I'm closing this issue for now, but don't hesitate to add a comment if you need further support on this.

@samyc1201 Thank you for the follow up!
