### ISSUE TITLE
easy-rules-for-android

### ISSUE THREAD

**Issue by cvdnn** [j-easy/easy-rules#314]
[EasyRules4Android](https://github.com/cvdnn/easy-rules-for-android.git) : A port of [EasyRules](https://github.com/j-easy/easy-rules.git) to Android by [@cvdnn](https://github.com/cvdnn)

**Comment by benas** [comment]
Hi @cvdnn ,

Thank you for this reference! Do we need a port of Easy Rules to android? Does this mean it's not possible to use it in android as is? In a previous version, Easy Rules used JMX APIs which were not supported in Android. But this has been removed in v3 and you should be able to use it in Android starting from v3 (See #173 and other JMX/Android related [issues](https://github.com/j-easy/easy-rules/issues?q=is%3Aissue+android+is%3Aclosed))

What changes have you made in your port? Unless I missed something, I don't see any difference from the original repository apart from this [Log](https://github.com/cvdnn/easy-rules-for-android/blob/main/easy-rules-core/src/main/java/org/jeasy/rules/core/Log.java) class.

**Comment by cvdnn** [comment]
Ashamed, as you can see, the compatibility of the current version of easy-rule is better. In order to allow more Android development to integrate easy-rule quickly and conveniently, currently only the easy-rule source code is migrated, and To write an example, there is no substantial optimization.

**Comment by benas** [comment]
ok thanks for the updates. 

> the compatibility of the current version of easy-rule is better

>  there is no substantial optimization.

In that case, I'm closing this issue. Thank you for letting me know about your work anyway!
