### ISSUE TITLE
Custom message from the rule when the condition is false

### ISSUE THREAD

**Issue by srkarnati** [j-easy/easy-rules#318]
Hello: Thanks for this awesome simple rules engine. I have a use case where when the condition is false, I want to get custom message from the rule indicating the cause. It would be nice if the return type (of condition) is parameterized type (or a richer type) rather than simple boolean.

Due to this limitation, right now, I am doing like below (not elegant):
```
@Component
@Rule(name="Mileage Rule", description="Vehicle's mileage must be less than configured max.")
public class Mileage {
  private SystemConfigService systemConfigService;

  public Mileage(SystemConfigService systemConfigService) {
    this.systemConfigService = systemConfigService;
  }

  @Condition
  public boolean when(@Fact("vehicle") Vehicle vehicle) {
   Integer maxMileage = systemConfigService.getMaxMileage();
    boolean condition = vehicle.getMileage() < maxMileage;
    if (!condition) {
      throw new RuntimeException(String.format("Vehicle's mileage %d is more than max allowed %d.", vehicle.getMileage(), maxMileage));
    }
    return condition;
  }

  @Action
  public void then() {
    // no-op
  }
}
```

instead, my expectation is to do something like below

```...
    @Condition
    public RuleEvaluationResponse when(@Fact("vehicle") Vehicle vehicle) {
      String failureMessage = String.format("Vehicle's mileage %d is more than max allowed %d.", vehicle.getMileage(), 
           maxMileage);
      Integer maxMileage = systemConfigService.getMaxMileage();
      boolean condition = vehicle.getMileage() < maxMileage;
      
     return new RuleEvaluationResponse(condition, condition ? null : failureMessage);

    }
...
```

Appreciate your thoughts.
Thanks, Srini

**Comment by benas** [comment]
Hi @srkarnati 

> Thanks for this awesome simple rules engine.

Thank you!

I see that your rule does not have any action (`no-op`)? Is that intended? This is a sign that your rule is not well designed or  the code you are trying to write as a rule is probably not suitable to be written as a rule.

Have you considered inverting the condition and throwing an exception from the action? Something like:

```java
@Component
@Rule(name="Mileage Rule", description="Vehicle's mileage must be less than configured max.")
public class Mileage {
  private SystemConfigService systemConfigService;

  public Mileage(SystemConfigService systemConfigService) {
    this.systemConfigService = systemConfigService;
  }

  @Condition
  public boolean when(@Fact("vehicle") Vehicle vehicle) {
     Integer maxMileage = systemConfigService.getMaxMileage();
     return vehicle.getMileage() >= maxMileage;
  }

  @Action
  public void then(@Fact("vehicle") Vehicle vehicle) {
     String message = String.format("Vehicle's mileage %d is more than max allowed %d.", vehicle.getMileage(), maxMileage);
     throw new Exception(message); // This can be consumed in RuleListener#onFailure(Rule rule, Facts facts, Exception exception)
  }
}
```

This seems more "natural" to me. Do you agree?

The type you are suggesting to add (`RuleEvaluationResponse`) could only be consumed in a listener anyway, something like `RuleListener#afterEvaluate(Rule rule, Facts facts, RuleEvaluationResponse evaluationResult)`  (which is a breaking change BTW), but as shown previously, you can achieve what you are looking for with the current version.

**Comment by LaurentSouchet-Orange** [comment]
For our project, we encountered the same need for a message return per rule tested with negative feedback.

_First method:_
To solve this need, we set up a first way.

We use the return of rulesEngine.check(rules, facts); 
It's a map <Rule, Boolean>.
If boolean is false we get name of Rule. 
We have associated an error key exactly with the same name.
All errors are defined in a property file.

But with this method, if we need to start rulesEngines.fire(rules, facts); then validation is another tested. 

_Second method:_ 

We want start rulesEngine.fire(rules, facts) directly, not use check(rules, facts) before.

Define a generic Rule like this.
@Getter
@Setter
public abstract class BasicRule {
    boolean executed;
}

In validation method, executed = false;
In last execution methode, executed = true;

All rules inherit from BasicRule.

We test after rulesEngine.fire(rules, facts) all rules to see if rule is executed or not.
If rule is not executed then we get name of Rule. 
We have associated an error key exactly with the same name.
All errors are defined in a property file.

**Comment by srkarnati** [comment]
Apologize for much delayed response on this. Thank you @benas and @LaurentSouchet-Orange for your comments.

Yes, understandably, what I requested is a breaking change. I toyed with the idea of overriding the DefaultRulesEngine, but didn't find it to be elegant.

Most of the rules I have are the validation type of rules (as opposed to biz type of rules), hence no logic in action. And also, upon rule failure, the failure message contains info from the facts too as that get piped to analytics engine. All these rules are managed beans in the spring container. So, for now, I am handling the return of failure message through custom exception in the "when" impl.

**Comment by benas** [comment]
@srkarnati 

> So, for now, I am handling the return of failure message through custom exception in the "when" impl.

So this is basically the approach you shared in your initial comment. You used the term `failure message`, but I don't consider a condition that evaluates to `false` as a failure. At least, in ER this is not considered as a failure, this means the rule is not triggered. What is considered as a failure is a rule that is triggered (condition evaluated to true) and its action fails (by throwing an exception).

So if you consider this as a failure, you should be really throwing the exception from the action method instead of doing it in the condition method (and using an empty action method).

Data validation is a typical use case for a rules engine (especially when there are many validation rules) where exceptions are thrown for any violated rule. So I still believe that in your case (which is "validation-oriented"), it is more appropriate to design rules with a side-effect free evaluation method (just test facts against the business condition), and an action that throws an exception for any validation error (with a correctly interpolated error message based on the given facts, as shown in the previous example).

For use cases where rules are not "validation-oriented", one can add a fact for the evaluation result/message, something like:

```java
import org.jeasy.rules.annotation.Action;
import org.jeasy.rules.annotation.Condition;
import org.jeasy.rules.annotation.Rule;
import org.jeasy.rules.api.Facts;
import org.jeasy.rules.api.Rules;
import org.jeasy.rules.api.RulesEngine;
import org.jeasy.rules.core.DefaultRulesEngine;

public class Launcher {

    public static void main(String[] args) {

        // create facts
        Facts facts = new Facts();
        facts.put("temperature", 25);

        // create rules
        Rules rules = new Rules();
        rules.register(new TemperatureRule());

        // create a rules engine and fire rules on known facts
        RulesEngine rulesEngine = new DefaultRulesEngine();
        rulesEngine.fire(rules, facts);
        
        // consume facts as needed to extract evaluation result/message
        System.out.println("facts = " + facts);
        // print: facts = [
        //  Fact{name='TemperatureRule_evaluationResult', value=false},
        //  Fact{name='TemperatureRule_evaluationMessage', value=temperature was 25},
        //  Fact{name='temperature', value=25}]
    }

    @Rule
    public static class TemperatureRule {

        @Condition
        public boolean when(Facts facts) {
            int temperature = facts.get("temperature");
            boolean evaluationResult = temperature > 30;
            if (!evaluationResult) { // could be done in a rule listener if we want a have a pure, side-effect free evaluation method.
                facts.put("TemperatureRule_evaluationResult", false);
                facts.put("TemperatureRule_evaluationMessage", "temperature was " + temperature); // the message could be defined in a property file
            }
            return evaluationResult;
        }

        @Action
        public void then() {
            // hypothetical action
            // aircoSystem.decreaseTemperature();
        }

    }
}
```

Facts can be consumed in a rule listener or even outside the rules engine as shown in this example. This approach also shows that we don't really need a rich return type for the evaluation method.

@LaurentSouchet-Orange Thank you for sharing your feedback on this! Your methods are also valid and this `error key = rule name` is actually a nice naming convention (as long as messages are correctly interpolated with current fact values). The sample above uses a similar approach.
