### ISSUE TITLE
SpEL rule cannot handle 2 facts in the same rule

### ISSUE THREAD

**Issue by guidoipsy** [j-easy/easy-rules#323]
Hello, I cannot make this rule work, I don't know if I making something wrong. 

**_.when(" #{ ['userTraitService_lifecycle'].?[ id == ['currentCycle_GBP'].id ].size() > 0 }")_**

If I remove the **['currentCycle_GBP'].id** and hardcode it with a valid id, it work, also **['currentCycle_GBP'].id** is used in another rule with out problems.

But the general idea is:
- userTraitService_lifecycle is a list of objects
- currentCycle_GBP is a simple object
- The general idea for the rule is that, there is at least 1 element with the currentCycle_GBP.id return true
- All facts element can be accessed individually but when I put them in one rule it evaluation fails

**Comment by benas** [comment]
This seems like a SpEL syntax issue. Please provide a minimal example that reproduces the issue or a failing unit test to be able to help you.
