### ISSUE TITLE
why not use Rule and facts as template ?

### ISSUE THREAD

**Issue by sarahBuisson** [j-easy/easy-rules#325]
why using a facts class, instead of using template for the Rule?

```
interface Rule<FactType>{

   boolean evaluate(facts:FactType) ...

}
```

It's a lot of file to update, but still, it's a quick change to do, and the test and tutorial could be adapt by using Facts as default FactType,  same for the jexl, mvel, spel project

If you are interested I can do it quickly

**Comment by benas** [comment]
What would be the added value of this design? Why would a `Rule` need to be generic? As far as a rule is concerned, it should evaluate a condition against a set of facts and then execute (or not) one or more actions on those facts, regardless of their types. Fact types are an implementation detail that should not be leaked in the `Rule` contract. 

A `Facts` object encapsulates a set of facts and does not need to be generic neither. What should be generic though is a single fact, as the fact type may vary from one fact to another (see the reasons of introducing `Fact<T>` in #276).

**Comment by benas** [comment]
Closing this issue, for the reasons explained in my previous comment.
