### ISSUE TITLE
Condition and Actions instead of lambda

### ISSUE THREAD

**Issue by sarahBuisson** [j-easy/easy-rules#326]
why use class Condition and Actions instead of  using Lambda? Those class contains only 1 method

**Comment by benas** [comment]
> why use class Condition and Actions instead of using Lambda?

Those classes were introduced in Easy Rules v3 which was based on Java 7 (no lambdas yet at that point)

> Those class contains only 1 method

Yes, that's why when v4 was released (which is based on Java 8), those classes were annotated with `@FunctionalInterface` (see ab1064a5530363a260e5f5a40115e9d42bf1a1b2).
