### ISSUE TITLE
In `easy-flow`, Whether multiple workflow types are supported in one workflow?

### ISSUE THREAD

**Issue by daidai21** [j-easy/easy-rules#328]
I'm sorry. The repository of easy-flows has been archived, can't create issue. So, I created in here.

In [easy-flow](https://github.com/j-easy/easy-flows), Whether multiple workflow types are supported in one workflow?

example: Approval workflow platform. This workflow instance include SequentialFlow, ParallelFlow and ConditionalFlow.

Thank you.

**Comment by benas** [comment]
Please do not ask questions about other projects here. There are 208 members watching this repository who might not be interested in this kind of support requests that are not related to Easy Rules, so let's respect them.

If a project has been archived, it has been archived for a good reason: I do not intend to maintain it anymore or provide support for it. Thank you for your comprehension.
