### ISSUE TITLE
NPE in DefaultRulesEngine when Rules/Facts are null

### ISSUE THREAD

**Issue by aston2016** [j-easy/easy-rules#329]
<dependency>
    <groupId>org.jeasy</groupId>
    <artifactId>easy-rules-core</artifactId>
    <version>4.1.0</version>
</dependency>

DefaultRulesEngine defaultEngine = new DefaultRulesEngine();
defaultEngine.fire(new Rules(), null);

The above code will report a NullPointerException

**Comment by benas** [comment]
Fixed in #335 .
