### ISSUE TITLE
Use Expression Language to define rules

### ISSUE THREAD

**Issue by benas** [j-easy/easy-rules#36]
It should be possible to define rules with an Expression Language (like OGNL, MVEL, JBoss EL, Spring EL).

Conditions are easy to express using an expression language.
The challenge here is how to define actions, their order, on which facts do they act, etc...

Still need to investigate and find a clean (and easy!) way to express actions.

Any suggestions or ideas are welcome!

**Comment by pats** [comment]
any chance for that feature in near future?

**Comment by benas** [comment]
Hi,

To be honest, not sure.
With all major changes planned for v3, I can't give you a precise answer.

Any contribution is welcome!

Kind regards
Mahmoud

**Comment by benas** [comment]
A possible solution would be to have a rules descriptor file, something like:

```json
[
 {
   "name": "my rule",
   "facts": [ "person", "account"],
   "condition": "EL",
   "actions": [
       { "action": "EL", "order": 1 },
       { "action": "EL", "order": 2 }
   ]
 }
]
```

And then create a rule proxy from this definition. EL in condition/actions should operate on declared facts. for example:

* condition: "person.age > 18"
* action: "account.balance = 0"

**Comment by jinjingfarm** [comment]
Suggestion: action could be defined to call a predefined rule function using one or more facts defined in the facts section to take an "in-direct" action.

**Comment by benas** [comment]
Hi @jinjingfarm 

Thank you for this suggestion! Where would this predefined rule function be defined?

**Comment by jinjingfarm** [comment]
Rule function could be part of a RuleEngine implementation or from outside through a factory. As far as a standard fact processing interface is defined, it would be helpful to deal with some complex situations, doing little bit more than { action: "account.balance = 0" }.

**Comment by benas** [comment]
Ok, I see. Interesting indeed. We can register functions through a factory at engine creation time. These functions can then be used in rules actions. Great suggestion! thank you. I'll add that to the feature 👍

**Comment by jinjingfarm** [comment]
Looking forward to this new feature. Thanks a lot.

**Comment by wangwei86609** [comment]
Hi @jinjingfarm
I recommend a better rule & flow engine to you, https://github.com/wangwei86609/osmanthus
It is more convinent than easy rules

**Comment by benas** [comment]
@wangwei86609 I added a comment in #103 . Let's continue the discussion there and keep this issue focused on EL.

@jinjingfarm If you want to give feedback or discuss about "osmanthus", please join the discussion in #103 

Kind regards
Mahmoud

**Comment by jinjingfarm** [comment]
@benas I like your decoupled component approach. One can always integrate these components together to build a more complex system.

**Comment by benas** [comment]
After introducing `Condition` and `Action` APIs in #119 , it is now possible to use any EL library with Easy Rules!

For example, we have added a [module](https://github.com/j-easy/easy-rules/tree/master/easy-rules-mvel) to use [MVEL](https://github.com/mvel/mvel) to define conditions and actions on given facts. Here is an example:

```java
// given
Condition isAdult = new MVELCondition("person.age > 18");
Facts facts = new Facts();
facts.put("person", new Person("foo", 20));

// when
boolean evaluationResult = isAdult.evaluate(facts);

// then
assertThat(evaluationResult).isTrue();
```

```java
// given
Action markAsAdult = new MVELAction("person.setAdult(true);");
Facts facts = new Facts();
Person foo = new Person("foo", 20);
facts.put("person", foo);

// when
markAsAdult.execute(facts);

// then
assertThat(foo.isAdult()).isTrue();
```

This makes it possible to store/load rules to/from an external resource (file, database, etc) and change them without recompiling the code. This is a huge improvement to Easy Rules.

@jinjingfarm In regards to predefined function, it will be added in a future release. Step by step..

@pats Almost done with v3.1. It will be ready for Christmas 😄 You can already try it with the current snapshot version and give your feedback. Keep tuned.

**Comment by benas** [comment]
@pats v3.1 is out! You can find a complete MVEL example in the [shop tutorial](https://github.com/j-easy/easy-rules/wiki/shop).
