### ISSUE TITLE
Is the Rules example by setting the result in the Rule class itself correct?

### ISSUE THREAD

**Issue by thomas2977** [j-easy/easy-rules#392]
Referring to FAQ's https://github.com/j-easy/easy-rules/wiki/faqs
"2. I would like to return a value upon a rule execution, how to do that?"

If rules are stateless, how can we set the execution result in the Rule itself?

**Comment by thomas2977** [comment]
Any updates? @fmbenhassine

**Comment by dvgaba** [comment]
You can update objects which are part of facts, see [example](https://github.com/j-easy/easy-rules/blob/d4450831533e47a5c0cb361edb80dad43db228a4/easy-rules-tutorials/src/main/java/org/jeasy/rules/tutorials/airco/DecreaseTemperatureAction.java#L39)

**Comment by thomas2977** [comment]
Thanks @dvgaba
