### ISSUE TITLE
Add RulesEvaluator API

### ISSUE THREAD

**Issue by benas** [j-easy/easy-rules#42]
As discussed in #40 with @thecederick , it may be useful to have a rules evaluator API to be able check rules like: `(RuleA and RuleB) or RuleC`

> You can already do this: ( ruleA.evaluate() && ruleB.evaluate() ) || ruleC.evaluate() . Do you believe Easy Rules should provide a RuleEvaluator API?

It is not always possible do it like you described, for example @Condition annotation and you do it outside of Engine.

**Comment by pdincau** [comment]
@benas it would be cool to be able to evaluate a set of rules and get back a list containing a rule result where you can see at least which rule evaluation failed...what do you think?

**Comment by benas** [comment]
Hi @pdincau 

Have you seen the [`checkRules`](https://github.com/EasyRules/easyrules/blob/master/easyrules-core/src/main/java/org/easyrules/api/RulesEngine.java#L83) method ?

I think this method is what you are looking for.

Kind regards
Mahmoud

**Comment by pdincau** [comment]
thanks @benas !

**Comment by benas** [comment]
@pdincau FYI, you can try the `checkRules` method with version 2.3.0-SNAPSHOT which is not released yet. I'm preparing to release it soon.

**Comment by pdincau** [comment]
@benas Yeah I was using previous tagged version and therefore i couldn't find the method neither on code nor in the docs. Thank you for your help 👍

**Comment by benas** [comment]
Sorry about that, I should have gave you this detail in my first comment. You can add [this repository](https://github.com/EasyRules/easyrules#current-version) and use the snapshot version.
