### ISSUE TITLE
@SpringRule annotation doesn't seem to work

### ISSUE THREAD

**Issue by careerscale** [j-easy/easy-rules#68]
Hi,

I am trying to use @SpringRule for easy rules Rule definition class, but I get this error (with 2.4.0 of easyrules).

java.lang.IllegalArgumentException: Rule 'xxx.xxxx.xxxx.BusinessLeaderRule$$EnhancerBySpringCGLIB$$2899f8a' is not annotated with 'org.easyrules.annotation.Rule'
	at org.easyrules.core.RuleDefinitionValidator.checkRuleClass(RuleDefinitionValidator.java:55)
	at org.easyrules.core.RuleDefinitionValidator.validateRuleDefinition(RuleDefinitionValidator.java:47)
	at org.easyrules.core.RuleProxy.asRule(RuleProxy.java:59)
	at org.easyrules.core.DefaultRulesEngine.registerRule(DefaultRulesEngine.java:81)
	at com.callidus.mlm.service.internal.VolumeServiceImpl.updateVolumes(VolumeServiceImpl.java:179)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)

Am I missing something? annotated the BusinessLeaderRule with @SpringRule

**Comment by careerscale** [comment]
@benas  can you please advise if I am doing something wrong?

**Comment by benas** [comment]
Hi,

Here is a complete example which is working fine with v2.4.0;

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.test</groupId>
    <artifactId>easyrules-spring-test</artifactId>
    <version>1.0-SNAPSHOT</version>

    <dependencies>
        <dependency>
            <groupId>org.easyrules</groupId>
            <artifactId>easyrules-spring</artifactId>
            <version>2.4.0</version>
        </dependency>
    </dependencies>

</project>
```

```java
package org.test;

import org.easyrules.annotation.Action;
import org.easyrules.annotation.Condition;
import org.easyrules.spring.SpringRule;

@SpringRule
public class DummyRule {

    @Condition
    public boolean when() {
        return true;
    }

    @Action
    public void then(){
        System.out.println("Hey, I'm managed by Spring");
    }
}
```

```java
package org.test;

import org.easyrules.api.RulesEngine;
import org.easyrules.core.RulesEngineBuilder;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;

public class Launcher {

    public static void main(String[] args) throws Exception {
        ApplicationContext context = new AnnotationConfigApplicationContext("org.test");
        DummyRule dummyRule = context.getBean(DummyRule.class);

        RulesEngine rulesEngine = RulesEngineBuilder.aNewRulesEngine().build();
        rulesEngine.registerRule(dummyRule);
        rulesEngine.fireRules();
    }

}
```

When I run the Launcher class, I get this:

```
Apr 20, 2017 9:00:29 AM org.springframework.context.annotation.AnnotationConfigApplicationContext prepareRefresh
INFO: Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@20ad9418: startup date [Thu Apr 20 09:00:29 CEST 2017]; root of context hierarchy
Apr 20, 2017 9:00:29 AM org.easyrules.core.DefaultRulesEngine logEngineParameters
INFO: Engine name: engine
Apr 20, 2017 9:00:29 AM org.easyrules.core.DefaultRulesEngine logEngineParameters
INFO: Rule priority threshold: 2,147,483,647
Apr 20, 2017 9:00:29 AM org.easyrules.core.DefaultRulesEngine logEngineParameters
INFO: Skip on first applied rule: false
Apr 20, 2017 9:00:29 AM org.easyrules.core.DefaultRulesEngine logEngineParameters
INFO: Skip on first non triggered rule: false
Apr 20, 2017 9:00:29 AM org.easyrules.core.DefaultRulesEngine logEngineParameters
INFO: Skip on first failed rule: false
Apr 20, 2017 9:00:29 AM org.easyrules.core.DefaultRulesEngine logRegisteredRules
INFO: Registered rules:
Apr 20, 2017 9:00:29 AM org.easyrules.core.DefaultRulesEngine logRegisteredRules
INFO: Rule { name = 'DummyRule', description = 'when when then then', priority = '2147483646'}
Hey, I'm managed by Spring
Apr 20, 2017 9:00:29 AM org.easyrules.core.DefaultRulesEngine applyRules
INFO: Rules evaluation started
Apr 20, 2017 9:00:29 AM org.easyrules.core.DefaultRulesEngine applyRules
INFO: Rule 'DummyRule' triggered
Apr 20, 2017 9:00:29 AM org.easyrules.core.DefaultRulesEngine applyRules
INFO: Rule 'DummyRule' performed successfully
```

Does this help?

kr
Mahmoud

**Comment by careerscale** [comment]
@benas I faced problem because of my Rule class was extending another class.  If there is no base class for it, it works pretty much fine.

thank you

**Comment by benas** [comment]
Ah ok, sorry for that.

Looks like this is related to #71 .

I've added `@Inherited` to `@SpringRule` annotation in version 5.1.0-SNAPSHOT.

@careerscale Could you please give it a try and tell me if it is ok for you now?

Kr
Mahmoud

**Comment by benas** [comment]
To use a snapshot version, please add sonatype's repo as described [here](https://github.com/EasyRules/easyrules#current-version)

**Comment by benas** [comment]
> I faced problem because of my Rule class was extending another class

@careerscale Have you got a chance to test after adding the `@Inherited` annotation?

**Comment by benas** [comment]
No update, I'm closing this issue.

@careerscale v2.5.0 is released. If the issue persists with this new version, please reopen it.

BTW, FYI, spring support has been deprecated ( more details on this decision in #74 )
