### ISSUE TITLE
Returning a value from a Rule

### ISSUE THREAD

**Issue by giridharshankar** [j-easy/easy-rules#70]
Hello,

    I like the simple rule engine offered by EasyRules.  I am planning to use this library to build Rules (simple, composite) that would evaluate various conditions and return some values after firing a rule.  Currently, fireRules() is a void method.  However, since private class variables are allowed in a Rule, is there a way I can set some state and I can access them after fireRules() to continue with a business context set after firing relevant rule(s)?

     Secondly, I plan to use this rule engine within my stateless session bean.  Every time a bean is allocated from the pool, it may trigger the rule engine, that would register relevant rules and fire rules.  Are the rule objects pooled in this library?  What is the lifecycle of a Rule object?  When the underlying Rule.java is updated, does the RuleEngine load the Rule class from the file system (latest) always or is this cached?

      Lastly, if I store the Rule itself in a JSON column in RDBMS like postgres, does RuleEngine support loading rules via JDBC/JPA from a table read?  Is there a plan to support this?

Thanks,
Giri

**Comment by benas** [comment]
Hi,

Sorry for the late reply.

> is there a way I can set some state and I can access them after fireRules() to continue with a business context set after firing relevant rule(s)?

You can still achieve that. See [Q2 on the FAQs section](http://www.easyrules.org/get-involved/faq.html#2)

> Are the rule objects pooled in this library?

No, each rules engine has its own registry of rules

> What is the lifecycle of a Rule object?

You create a rule, register it in the rules engine. From that moment, it's life cycle is the same as the rules engine

> does the RuleEngine load the Rule class from the file system

No, rules are java objects created at runtime.

Hope this helps.

Kr
Mahmoud

**Comment by benas** [comment]
Any update on this?

**Comment by benas** [comment]
@giridharshankar 

> is there a way I can set some state and I can access them after fireRules() to continue with a business context set after firing relevant rule(s)?

Starting from v3, you can use the `Facts` API to access known facts before or after firing rules.

I'm closing this issue for now, if you have any other question, you can still ask them here.

**Comment by 3amprogrammer** [comment]
Hello @benas,
as the above link is dead, could you please elaborate on accessing return value from rules execution? Should I put some map inside a facts and put the result after each execution from within the each rule?

Another question, but closely related to this issue is what you think of different execution strategies? Lets say I want to have the max value from all rules, or reduce rules to get the sum of all rules? Should I take the same approach as I have described above, or maby sobie strategy design pattern would be appropriate?

The background for the above questions is I use this Rule Engine to compute complicated discounts and fees - maby that helps.

Merry Christmas :)

**Comment by pallavialuri** [comment]
Hi I am trying to implement composite rules in my yaml file.. but i am getting an error when i am trying to read my yaml file. Please help me in resolving the issue.. i am using the yaml file reader to read the file and createRules method.. please let me know where i am going wrong.. please find the files attached

[compositerule.zip](https://github.com/j-easy/easy-rules/files/3393958/compositerule.zip)

thank you in advance
