### ISSUE TITLE
Port of EasyRules in Go

### ISSUE THREAD

**Issue by jiminoc** [j-easy/easy-rules#78]
love your library! I did a port of it over to Go. I was hoping to get some eyes on it to see if I missed anything I should include. 

thanks :)

https://github.com/CrowdStrike/easyrulesgo

**Comment by benas** [comment]
Hi @jiminoc 

I'm glad you like Easy Rules.
It's great to see your go implementation! I'm a beginner at go but I will follow your repo closely.
Please don't hesitate to ask me if you have any question so I can help.

May I ask you to add a link to your repo in Easy Rules home page?

Kind regards
Mahmoud

**Comment by benas** [comment]
I added a link to your repo in the readme. If this is a problem, please let me know and I'll remove it.

> I was hoping to get some eyes on it to see if I missed anything I should include.

One of the most significant additions in v3 is the `Facts` API. This has been requested by many users and actually makes the library more intuitive. But this is quite recent that's why it's not in the go implementation I guess.

Anyway, thank you for this port to golang!

**Comment by jiminoc** [comment]
I'll start reading up on the Facts stuff. I've had the Go port done for almost a year so I assume it's come since then. Do you have any reference links? I checked the open issues but only saw one reference to it 2 years ago. thanks for adding it!

**Comment by jiminoc** [comment]
looks I found this one https://github.com/j-easy/easy-rules/issues/37

**Comment by benas** [comment]
Yes indeed, it was initially described in issue #37 .

You can find other details in the wiki here: https://github.com/j-easy/easy-rules/wiki/defining-facts

I would love to help if you have any question.

Kind regards
Mahmoud

**Comment by benas** [comment]
I'm closing this issue for now.

If you have any question, please let me know, I would love to help!

**Comment by jiminoc** [comment]
sorry, I was away for a few days. I've been noodling on this and obviously go has some differences and can't do the same kind of annotations. I'll create an issue on the golang project and cc you to  move the convo there
