### ISSUE TITLE
For v3 before totaly migrating to Java 8 maybe we should have a transition version which supports Java 7

### ISSUE THREAD

**Issue by cgonul** [j-easy/easy-rules#80]
The new facts and rules abstraction which come with v3 is something that Java 7 users would want with their rule engines. Java 8-9 is undinable however lots of people still use java 7 these days especially if they had to maintain old  hevy enterprise applications . 

Before totally migrating to Java 8 we should have transition version which supports Java 7. Maybe in later times we can tag this modification in a seperate branch and name it the last version which supports java 7.

**Comment by cgonul** [comment]
You can assign it to me @benas

**Comment by benas** [comment]
You are right! I'm closing this issue since your PR has been merged.

Many thanks.

Kr
Mahmoud
