### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by joaomarri** [j-easy/easy-rules#82]
Hi,

I'm trying to use this api and found a NullPointerException in line 209 of DefaultRulesEngine.class:

 LOGGER.log(Level.INFO, format("Fact { %s : %s }", fact.getKey(), fact.getValue().toString()));

I want to pass null in fact value because my rule will check that condition 

tks,

**Comment by benas** [comment]
Hello @joaomarri 

Thank you for reporting this! Indeed the engine fails when a fact is null.

I've fixed this issue and uploaded a new snapshot version. Could you please give it a try and tell me if this is ok for you? Many thanks upfront.

Kind regards
Mahmoud

**Comment by joaomarri** [comment]
hello Mahmoud,

thank you very much, every thing is ok

Kind regards,
Joao

**Comment by benas** [comment]
Hi Joao,

Great! Thank you for your time testing the fix.

Keep tuned for the release.

Kr
Mahmoud
