### ISSUE TITLE
Class 'Facts' should have method 'put' instead or in addition to 'add'

### ISSUE THREAD

**Issue by will-gilbert** [j-easy/easy-rules#83]
The class "**Facts**" is a facade for the underlying``` Map``` methods of  ```get```, ```remove``` and ```toString```. While the '```add```' method, usually associated with a List, invokes the '```put```' method of the Map interface.

This feature request is to add a '```put```' method or rename the existing '```add```' method as 3.x is still under development.

The change has the impact on the Groovy Map usage so all of the following syntaxes can be used:

```
facts.put('thickness', 10)
facts['color'] = 'Blue'
facts.weight = 500
facts.'shape' = 'Circle'
facts << [price:150]
```

**Comment by benas** [comment]
You are right, `put` is better since `Facts` is backed by a map.
I've added a `put` method in the latest v3.0.0-SNAPSHOT.

The `add` method has been deprecated and will be removed in the final release to avoid any confusion.

**Comment by will-gilbert** [comment]
Great! Will modify the Groovy Tutorial tomorrow.
