### ISSUE TITLE
Rule Registration should know the type of data it would get executed on

### ISSUE THREAD

**Issue by khandelwalankit** [j-easy/easy-rules#85]
Hi Mahmoud,

I wanted to describe the complexities i faced during implementation of easy-rules in one of my projects. I will explain scenario and the implementation i did and we can discuss better solution for it and my suggestion to improve implementation in such scenario's.

**Scenario :** I am using rules engine to validate EDI document according to some business rules(for instance [EDI850](http://www.1edisource.com/transaction-sets?TSet=850) ). Here as you can see, an order has multiple items, each item has multiple discounts and multiple shipping details and payment details. 

**Bottleneck :** i could not register all the rules at once, i had to register all rules related to discount , iterate through them with different data, fire the rule during iteration and unregister the rules, this is the same process i followed for all the rules i had. This becomes clumsy if there is home grown documents with multiple hierarchies.
 
**Common Code:**  i find that for each domain rule to be executed i had to register rules for that domain, during each iteration feed the data to the rule, fire the rule and after the iteration unregister the rule. And follow the same process for another domain. 

I would like to have your opinion on how you would approach such problem with easy rules. 

**My Suggestion** : I know there is already an enhancement to disassociate data from rules and provide the data at runtime during firing of rules, i would like to suggest that in such cases, a rule engine _should register a rule with the type of data that rule should work upon_, once the registration is done, you would just need to feed data to rules and fire rules. This data that needs to be fed to rules in abstraction called ruleData.  The fire rules implementation should know which rule has found the data and fire only the rules which have received data. Once the rule has been fired with that data, the data needs to be removed from abstraction ruleData of that rule.

Let me know if you have confusion or question on any of these things.

**Comment by khandelwalankit** [comment]
Facts do answer this question till certain extent. I will redesign application with facts and see if there are any issues.

**Comment by benas** [comment]
Hey,

I was just writing an answer for this!

**Comment by benas** [comment]
Sorry I was busy the last few days focusing on the release, hence the late reply

**Comment by benas** [comment]
> I would like to have your opinion on how you would approach such problem with easy rules.

I would go with a different rules set and facts for each domain. You can reuse the same rules engine (unless you have specific rule listeners for each domain)

> you would just need to feed data to rules and fire rules.

This is the purpose of the new `Facts` API.

> The fire rules implementation should know which rule has found the data and fire only the rules which have received data

This is somehow forward chaining. I planned to add a new `InferenceRuleEngine` that would evaluate all rules on known facts, select rules that can be fired (use a conflict resolution strategy if many rules are applicable), fire rules, and repeat the process until no more rules are applicable. This is planned for v3.1.

What do you think of this planned addition?

**Comment by khandelwalankit** [comment]
Was going through 3.0.0 release and found it interesting. I am in alignment with thought process. I will try to implement it and see how it goes. I am concerned about rules which would take list of objects as input and not single object. 

Do you think a rule can have arbitrary number of facts (or arguments) in evaluate and execute phase? 

Reopening this thread for further clarification/discussion.
 
> select rules that can be fired (use a conflict resolution strategy if many rules are applicable), fire rules, and repeat the process until no more rules are applicable. 

Do you intend to maintain state of every rule to the data it has worked upon? I am not sure of what you mean by repeat the process until no more rules are applicable? - In my opinion a rule engine should be fed Data Flow Diagram(or in this case a Rule Flow Diagram) which would tell Rules engine what path to take.

**Comment by benas** [comment]
> I am concerned about rules which would take list of objects as input and not single object. Do you think a rule can have arbitrary number of facts (or arguments) in evaluate and execute phase?

This is possible, here is an example:
https://github.com/j-easy/easy-rules/blob/master/easy-rules-core/src/test/java/org/jeasy/rules/core/FactInjectionTest.java#L106

> Do you intend to maintain state of every rule to the data it has worked upon? I am not sure of what you mean by repeat the process until no more rules are applicable?

The state is maintained in the `Facts` object which is passed from a rule to the next one.

> I am not sure of what you mean by repeat the process until no more rules are applicable?

A good example of forward chaining here (see figure 1.2):

https://docs.jboss.org/drools/release/5.3.0.Final/drools-expert-docs/html/ch01.html

**Comment by khandelwalankit** [comment]
Thanks for clarifying it Mahmoud. It makes sense to have forward chaining in easy rules.

**Comment by benas** [comment]
Great! I'm glad it helped.

> Reopening this thread for further clarification/discussion.

If you don't have any other questions, please close this issue.

Kr
Mahmoud
