### ISSUE TITLE
Add skipOnMissingFact parameter

### ISSUE THREAD

**Issue by benas** [j-easy/easy-rules#89]
As of v3.0, if a declared fact is missing in a condition method, the engine will throw a runtime exception. This behaviour should be configurable to skip the rule in case a declared fact is missing.

The goal is to introduce a new parameter `skipOnMissingFact` to be able to change the default behaviour.

Note: this parameter cannot be used if a fact is missing in an action method (since the rule has been already fired and cannot be skipped anymore). For action methods, if a fact is missing, the engine will throw a runtime exception anyway.

**Comment by khandelwalankit** [comment]
Instead of defining the parameter, should this be a configuration of that rules engine? 

@RuleEngineConfig(
missingFactPolicy = ReportingPolicy.ERROR 
)  
The reportingPolicy can be ERROR, WARN, SKIP. Also, we can add different configuration to it which are present today for defining rules engine :
skipOnFirstFailedRule = true, false
I found such implementation in MapStruct library : http://mapstruct.org/documentation/dev/reference/html/#shared-configurations
which looks very neat. Let me know your thoughts.

**Comment by benas** [comment]
Thank you for this suggestion.

Where do you put the `@ruleengineconfig` annotation?

**Comment by khandelwalankit** [comment]
I think this should go in declaration of rulesEngine. Something like : 

@ruleengineconfig
private RulesEngine rulesEngine;

Did that answer your question?

**Comment by benas** [comment]
Yeah I see but where do this declaration is done? Who will introspect this annotation?

It is different from mapstruct where you annotate a class or interface.

Could you provide a complete example of how you expect to configure the engine with an annotation?

**Comment by khandelwalankit** [comment]
I think we would have to change classes RulesEngineParameter, RulesEngineBuilder and DefaultRulesEngine. What i am looking for is: 

```
@Target(ElementType.TYPE)
@Retention(RetentionPolicy.CLASS)
public @interface RulesEngineParameters {

    /**
     * The engine name.
     */
    @Deprecated
    String name() default "engine";
    
    /**
     * Parameter to skip next applicable rules when a rule is applied.
     */
    boolean skipOnFirstApplierRule() default false;

    /**
     * Parameter to skip next applicable rules when a rule is non triggered
     */
    boolean skipOnFirstNonTriggeredRule() default false;

    /**
     * Parameter to skip next applicable rules when a rule has failed.
     */
    boolean skipOnFirstFailedRule() default false;

    /**
     * Parameter to skip next rules if priority exceeds a user defined threshold.
     */
    int priorityThreshold() default Integer.MAX_VALUE;

    /**
     * Parameter to mute loggers.
     */
    boolean silentMode() default false;

}


@RulesEngineParameters(
name="ABC",
skipOnFirstFailedRule=true
)
public interface MyCustomConfig{
}


@rulesengineconfig(
config = MyCustomConfig.class
)
public class MyRulesEngine {
    private RulesEngine rulesEngine;
    private Rules rules;
    private Facts facts;
    private CustomRuleListener myRulesEngineRuleListener;

    private static class myRulesEngineInstantiator {
        private static MyRulesEngine INSTANCE = new MyRulesEngine();
    }

    public static RulesEngine getRulesEngine() {
        return myRulesEngineInstantiator.INSTANCE.rulesEngine;
    }

    public static Rules getRules() {
        return myRulesEngineInstantiator.INSTANCE.rules;
    }

    public static Facts getFacts() {
        return myRulesEngineInstantiator.INSTANCE.facts;
    }

    private MyRulesEngine() {
        this.myRulesEngineRuleListener = myRulesEngineRuleListener;
        this.rulesEngine = aNewRulesEngine().build();
        this.facts = new Facts();
        this.rules = new Rules();
    }
}

```
I think RulesEngineBuilder and/or DefaultRulesEngine should introspect this annotation.

**Comment by benas** [comment]
This is a lot of work just to set a boolean value. I have to write:

* an empty interface `MyCustomConfig`
* add an annotation on it `RulesEngineParameters`
* write a class for a rule engine `MyRulesEngine` (which encapsulates another rules engine)
* add an annotation on it `rulesengineconfig`
* and finally how to create it? How could `DefaultRulesEngine` introspect the annotation?

Mapstruct's approach works well for mapstruct where the user is supposed to create a mapping interface and annotate it. Here, the user is not supposed to create a rule engine class and annotate it to configure it. He can create an instance of one of the rules engine classes provided by easy rules (DefaultRuleEngine or InferenceRuleEngine) and configure it with `RulesEngineParameter` or using a the `RulesEngineBuilder`. Do you see the difference?

The goal of this issue is to add a boolean parameter in a consistent way with other parameters.

**Comment by khandelwalankit** [comment]
Yes you are right. This feels painful. We can add one more parameter to builder easily.
