### ISSUE TITLE
Changing logging level

### ISSUE THREAD

**Issue by cfollet** [j-easy/easy-rules#90]
Hi Mahmoud,

is it possible to change the logging level for INFO -> DEBUG for example? 

It seems to be [hard coded](https://github.com/j-easy/easy-rules/blob/master/easy-rules-core/src/main/java/org/jeasy/rules/core/DefaultRulesEngine.java#L97).

What are your thought about the logger level as a `RulesEngineParameter `?

**Comment by benas** [comment]
Hello,

> is it possible to change the logging level for INFO -> DEBUG for example?

Sure, you can start your JVM with a JUL config file (`-Djava.util.logging.config.file="logging.properties"`) and specify `.level= FINE` in it. There is no DEBUG level in JUL (this is so weird btw !!)

> It seems to be hard coded.

Not sure it is hard coded. It would be hard coded if it was something like:

```java
Logger log = LogManager.getLogManager().getLogger("org.jeasy.rules");
for (Handler h : log.getHandlers()) {
    h.setLevel(Level.INFO); // hard coded regardless of what you specify in an external properties file
}
```

May be the log level is not correct but this is another question.

> What are your thought about the logger level as a RulesEngineParameter?

I think this is related to the configuration of JUL, not the engine itself. So it is not really a parameter of the rules engine to add it to `RulesEngineParameters`. Do you agree?

**Comment by cfollet** [comment]
Hi,

Thanks you for your time and your explanation. 
I will use the solution you provided using `logging.properties`.

**Comment by swapson** [comment]
try

import org.slf4j.LoggerFactory;
import ch.qos.logback.classic.Level;
import ch.qos.logback.classic.Logger;

// disable logging
Logger log = (Logger) LoggerFactory.getLogger(Logger.ROOT_LOGGER_NAME);
log.setLevel(Level.OFF);
