### ISSUE TITLE
Why not use `rule instanceof Rule` ?

### ISSUE THREAD

**Issue by wg1j** [j-easy/easy-rules#97]
Hi, @benas:

I am a little confused about [`Utils.getInterfaces(rule).contains(Rule.class)`](https://github.com/j-easy/easy-rules/blob/master/easy-rules-core/src/main/java/org/jeasy/rules/core/RuleProxy.java#L64) in `RuleProxy`. In my simple test it is easier and faster to do a `instanceOf` instead of a `Utils.getInterfaces`

Why not use `rule instanceof Rule`? Could you explain it for me ?

#### Here is my test code:
```java
int count = 10000;
DummyRule rule = new DummyRule();
for (int j = 0; j < 100; j++) {
    long start1 = System.currentTimeMillis();
    for (int i = 0; i < count; i++) {
        boolean isRule = rule instanceof Rule;
    }
    System.out.println(j + "-cost-1: " + (System.currentTimeMillis() - start1));

    long start2 = System.currentTimeMillis();
    for (int i = 0; i < count; i++) {
        boolean isRule = Utils.getInterfaces(rule).contains(Rule.class);
    }
    System.out.println(j + "-cost-2: " + (System.currentTimeMillis() - start2));
}
```
#### Here is the result:
```
0-cost-1: 2
0-cost-2: 43
1-cost-1: 2
1-cost-2: 12
2-cost-1: 0
2-cost-2: 2
3-cost-1: 1
3-cost-2: 3
4-cost-1: 0
4-cost-2: 2
5-cost-1: 0
5-cost-2: 2
6-cost-1: 1
6-cost-2: 1
7-cost-1: 1
7-cost-2: 1
8-cost-1: 1
8-cost-2: 2
9-cost-1: 1
9-cost-2: 1
...
90-cost-1: 0
90-cost-2: 1
91-cost-1: 0
91-cost-2: 0
92-cost-1: 0
92-cost-2: 1
93-cost-1: 0
93-cost-2: 1
94-cost-1: 0
94-cost-2: 6
95-cost-1: 0
95-cost-2: 2
96-cost-1: 0
96-cost-2: 1
97-cost-1: 0
97-cost-2: 1
98-cost-1: 0
98-cost-2: 1
99-cost-1: 0
99-cost-2: 1
```

**Comment by benas** [comment]
> Why not use rule instanceof Rule? Could you explain it for me ?

To be honest, I don't remember. There should be a good reason for it, but may be not..

The goal of this test is to check if the given object is already a rule and if it is the case, don't create a proxy and return it as is. Now, how to check if an object is a rule? Either:

* it implements `Rule`
* it extends `BasicRule`
* is already a proxy
* Other possibility?

If `instance of` is enough for all these cases, we can use it! Don't hesitate to open a PR for it. It would be better than this poor utilitiy method.

BTW, I would use JMH for the benchmark.

**Comment by wg1j** [comment]
Hi, 

Thanks for your time and your explanation.
In my test, `instance of` can satisfy all your cases, and it is faster indeed. 
I also find a similar question in [stackoverflow](https://stackoverflow.com/questions/103564/the-performance-impact-of-using-instanceof-in-java/26514984#26514984), and get a [benchmark result](https://stackoverflow.com/revisions/26514984/10).

So that, maybe I was an evil. 😅 Sorry for trouble you!!

**Comment by benas** [comment]
Ok great, please open a PR with suggested changes.

> So that, maybe I was an evil

No in contrast! your contribution is valuable. Please go for it, be my guest. I'll be happy to merge your PR.

**Comment by wg1j** [comment]
Thanks!!
